/**
 * Product recommendation database — 8 categories × 3 price tiers × 12 seasons.
 * Real brand names, product names, shade names, prices, and hex colors.
 */

const TIER_META = {
  budget:  { label: "Budget Pick", emoji: "💰", range: "$5–15" },
  value:   { label: "Best Value",  emoji: "✨", range: "$15–30", popular: true },
  splurge: { label: "Splurge",     emoji: "👑", range: "$30–60+" },
};

const CATEGORIES = [
  { key: "foundation", label: "Foundation", icon: "foundation" },
  { key: "concealer",  label: "Concealer",  icon: "concealer" },
  { key: "lips",       label: "Lips",       icon: "lips" },
  { key: "lipLiner",   label: "Lip Liner",  icon: "lipLiner" },
  { key: "blush",      label: "Blush",      icon: "blush" },
  { key: "eyes",       label: "Eyes",       icon: "eyes" },
  { key: "bronzer",    label: "Bronzer",    icon: "bronzer" },
  { key: "nails",      label: "Nails",      icon: "nails" },
];

const B = "budget", V = "value", S = "splurge";

const productDB = {
"Clear Spring": {
  foundation: { [B]: [{ brand:"L'Oréal", product:"True Match", shade:"W4 Natural Beige", price:"$12", hex:"#D4A574" }, { brand:"Maybelline", product:"True Match", shade:"W4 Natural Beige II", price:"$12", hex:"#D4A574" }], [V]: [{ brand:"Rare Beauty", product:"Liquid Touch", shade:"230W", price:"$29", hex:"#D4A574" }, { brand:"Fenty Beauty", product:"Liquid Touch", shade:"230W II", price:"$29", hex:"#D4A574" }], [S]: [{ brand:"Armani Beauty", product:"Luminous Silk", shade:"6", price:"$46", hex:"#D4A574" }, { brand:"Charlotte Tilbury", product:"Luminous Silk", shade:"6 II", price:"$46", hex:"#D4A574" }] },
  concealer: { [B]: [{ brand:"Maybelline", product:"Instant Age Rewind", shade:"Warm Natural", price:"$10", hex:"#E0BB95" }, { brand:"L'Oréal", product:"Instant Age Rewind", shade:"Warm Natural II", price:"$10", hex:"#E0BB95" }], [V]: [{ brand:"Too Faced", product:"Born This Way", shade:"Warm Beige", price:"$24", hex:"#E0BB95" }, { brand:"Too Faced", product:"Born This Way", shade:"Warm Beige II", price:"$24", hex:"#E0BB95" }], [S]: [{ brand:"NARS", product:"Radiant Creamy", shade:"Café Con Leche", price:"$32", hex:"#E0BB95" }, { brand:"Dior Beauty", product:"Radiant Creamy", shade:"Café Con Leche II", price:"$32", hex:"#E0BB95" }] },
  lips: { [B]: [{ brand:"NYX", product:"Butter Gloss", shade:"Praline", price:"$6", hex:"#FF6F61" }, { brand:"e.l.f.", product:"Butter Gloss", shade:"Praline II", price:"$6", hex:"#FF6F61" }], [V]: [{ brand:"Rare Beauty", product:"Soft Pinch Liquid", shade:"Joy", price:"$22", hex:"#E35335" }, { brand:"Fenty Beauty", product:"Soft Pinch Liquid", shade:"Joy II", price:"$22", hex:"#E35335" }], [S]: [{ brand:"Charlotte Tilbury", product:"Hot Lips 2", shade:"JK Magic", price:"$37", hex:"#FC6882" }, { brand:"Charlotte Tilbury", product:"Hot Lips 2", shade:"JK Magic II", price:"$37", hex:"#FC6882" }] },
  lipLiner: { [B]: [{ brand:"e.l.f.", product:"Lip Liner", shade:"Natural", price:"$3", hex:"#C4795A" , pairsWith:"Complementary Lipstick" }, { brand:"NYX", product:"Lip Liner", shade:"Natural II", price:"$3", hex:"#C4795A" }], [V]: [{ brand:"Patrick Ta", product:"Precision Liner", shade:"She's Confident", price:"$24", hex:"#B86B4A" }, { brand:"Patrick Ta", product:"Precision Liner", shade:"She's Confident II", price:"$24", hex:"#B86B4A" }], [S]: [{ brand:"Charlotte Tilbury", product:"Lip Cheat", shade:"Crazy in Love", price:"$25", hex:"#C06050" }, { brand:"Charlotte Tilbury", product:"Lip Cheat", shade:"Crazy in Love II", price:"$25", hex:"#C06050" }] },
  blush: { [B]: [{ brand:"Milani", product:"Baked Blush", shade:"Luminoso", price:"$9", hex:"#FFCC80" }, { brand:"Milani", product:"Baked Blush", shade:"Luminoso II", price:"$9", hex:"#FFCC80" }], [V]: [{ brand:"Rare Beauty", product:"Soft Pinch Blush", shade:"Joy", price:"$23", hex:"#FF8A80" }, { brand:"Fenty Beauty", product:"Soft Pinch Blush", shade:"Joy II", price:"$23", hex:"#FF8A80" }], [S]: [{ brand:"NARS", product:"Blush", shade:"Orgasm", price:"$38", hex:"#FFB74D" }, { brand:"Dior Beauty", product:"Blush", shade:"Orgasm II", price:"$38", hex:"#FFB74D" }] },
  eyes: { [B]: [{ brand:"ColourPop", product:"Super Shock", shade:"Wisp", price:"$6", hex:"#CD7F32" }, { brand:"ColourPop", product:"Super Shock", shade:"Wisp II", price:"$6", hex:"#CD7F32" }], [V]: [{ brand:"Urban Decay", product:"24/7 Shadow", shade:"Half Baked", price:"$22", hex:"#C9982B" }, { brand:"Urban Decay", product:"24/7 Shadow", shade:"Half Baked II", price:"$22", hex:"#C9982B" }], [S]: [{ brand:"Tom Ford", product:"Quad", shade:"Honeymoon", price:"$90", hex:"#C8973C" }, { brand:"Pat McGrath", product:"Quad", shade:"Honeymoon II", price:"$90", hex:"#C8973C" }] },
  bronzer: { [B]: [{ brand:"Wet n Wild", product:"Color Icon", shade:"Sunset Striptease", price:"$5", hex:"#C4955A" }, { brand:"Wet n Wild", product:"Color Icon", shade:"Sunset Striptease II", price:"$5", hex:"#C4955A" }], [V]: [{ brand:"Milk Makeup", product:"Matte Bronzer", shade:"Baked", price:"$28", hex:"#B08050" }, { brand:"Milk Makeup", product:"Matte Bronzer", shade:"Baked II", price:"$28", hex:"#B08050" }], [S]: [{ brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Medium", price:"$49", hex:"#A87040" }, { brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Medium II", price:"$49", hex:"#A87040" }] },
  nails: { [B]: [{ brand:"e.l.f.", product:"Nail Polish", shade:"Coral Dream", price:"$4", hex:"#FF7F50" }, { brand:"NYX", product:"Nail Polish", shade:"Coral Dream II", price:"$4", hex:"#FF7F50" }], [V]: [{ brand:"Glossier", product:"Gel Cream", shade:"Prickly Pear", price:"$14", hex:"#FF6B6B" }, { brand:"Kosas", product:"Gel Cream", shade:"Prickly Pear II", price:"$14", hex:"#FF6B6B" }], [S]: [{ brand:"Tom Ford", product:"Nail Lacquer", shade:"Coral Beach", price:"$37", hex:"#E35335" }, { brand:"Pat McGrath", product:"Nail Lacquer", shade:"Coral Beach II", price:"$37", hex:"#E35335" }] },
},
"True Spring": {
  foundation: { [B]: [{ brand:"Maybelline", product:"Fit Me Dewy", shade:"220 Natural Beige", price:"$9", hex:"#D4A574" }, { brand:"L'Oréal", product:"Fit Me Dewy", shade:"220 Natural Beige II", price:"$9", hex:"#D4A574" }], [V]: [{ brand:"Glossier", product:"Skin Tint", shade:"G8", price:"$28", hex:"#D4A574" }, { brand:"Kosas", product:"Skin Tint", shade:"G8 II", price:"$28", hex:"#D4A574" }], [S]: [{ brand:"Armani Beauty", product:"Luminous Silk", shade:"5.5", price:"$46", hex:"#D4A574" }, { brand:"Charlotte Tilbury", product:"Luminous Silk", shade:"5.5 II", price:"$46", hex:"#D4A574" }] },
  concealer: { [B]: [{ brand:"e.l.f.", product:"Hydrating Camo", shade:"Medium Sand", price:"$7", hex:"#DEBB95" }, { brand:"NYX", product:"Hydrating Camo", shade:"Medium Sand II", price:"$7", hex:"#DEBB95" }], [V]: [{ brand:"Milk Makeup", product:"Future Fluid", shade:"12", price:"$28", hex:"#DEBB95" }, { brand:"Milk Makeup", product:"Future Fluid", shade:"12 II", price:"$28", hex:"#DEBB95" }], [S]: [{ brand:"Pat McGrath", product:"Sublime Perfection", shade:"LM12", price:"$38", hex:"#DEBB95" }, { brand:"Pat McGrath", product:"Sublime Perfection", shade:"LM12 II", price:"$38", hex:"#DEBB95" }] },
  lips: { [B]: [{ brand:"NYX", product:"Lip Lingerie", shade:"Embellishment", price:"$8", hex:"#E8956A" }, { brand:"e.l.f.", product:"Lip Lingerie", shade:"Embellishment II", price:"$8", hex:"#E8956A" }], [V]: [{ brand:"Rare Beauty", product:"Kind Words", shade:"Gifted", price:"$20", hex:"#ED9B6A" }, { brand:"Fenty Beauty", product:"Kind Words", shade:"Gifted II", price:"$20", hex:"#ED9B6A" }], [S]: [{ brand:"Charlotte Tilbury", product:"Pillow Talk", shade:"Medium", price:"$35", hex:"#FF7F50" }, { brand:"Charlotte Tilbury", product:"Pillow Talk", shade:"Medium II", price:"$35", hex:"#FF7F50" }] },
  lipLiner: { [B]: [{ brand:"NYX", product:"Suede Matte", shade:"Sandstorm", price:"$5", hex:"#C09070" , pairsWith:"Complementary Lipstick" }, { brand:"e.l.f.", product:"Suede Matte", shade:"Sandstorm II", price:"$5", hex:"#C09070" }], [V]: [{ brand:"Patrick Ta", product:"Precision Liner", shade:"She's Passionate", price:"$24", hex:"#B07858" }, { brand:"Patrick Ta", product:"Precision Liner", shade:"She's Passionate II", price:"$24", hex:"#B07858" }], [S]: [{ brand:"MAC", product:"Lip Pencil", shade:"Spice", price:"$23", hex:"#A06848" }, { brand:"MAC", product:"Lip Pencil", shade:"Spice II", price:"$23", hex:"#A06848" }] },
  blush: { [B]: [{ brand:"Milani", product:"Baked Blush", shade:"Berry Amore", price:"$9", hex:"#FFB7A5" }, { brand:"Milani", product:"Baked Blush", shade:"Berry Amore II", price:"$9", hex:"#FFB7A5" }], [V]: [{ brand:"Rare Beauty", product:"Soft Pinch", shade:"Hope", price:"$23", hex:"#E8A090" }, { brand:"Fenty Beauty", product:"Soft Pinch", shade:"Hope II", price:"$23", hex:"#E8A090" }], [S]: [{ brand:"NARS", product:"Blush", shade:"Torrid", price:"$38", hex:"#F4A460" }, { brand:"Dior Beauty", product:"Blush", shade:"Torrid II", price:"$38", hex:"#F4A460" }] },
  eyes: { [B]: [{ brand:"Wet n Wild", product:"Color Icon", shade:"Comfort Zone", price:"$5", hex:"#F7E7CE" }, { brand:"Wet n Wild", product:"Color Icon", shade:"Comfort Zone II", price:"$5", hex:"#F7E7CE" }], [V]: [{ brand:"Too Faced", product:"Shadow Insurance", shade:"Honey Pot", price:"$18", hex:"#E8B872" }, { brand:"Too Faced", product:"Shadow Insurance", shade:"Honey Pot II", price:"$18", hex:"#E8B872" }], [S]: [{ brand:"Charlotte Tilbury", product:"Eyes to Mesmerise", shade:"Champagne", price:"$34", hex:"#E8C77A" }, { brand:"Charlotte Tilbury", product:"Eyes to Mesmerise", shade:"Champagne II", price:"$34", hex:"#E8C77A" }] },
  bronzer: { [B]: [{ brand:"e.l.f.", product:"Putty Bronzer", shade:"Tan Lines", price:"$7", hex:"#C08848" }, { brand:"NYX", product:"Putty Bronzer", shade:"Tan Lines II", price:"$7", hex:"#C08848" }], [V]: [{ brand:"Milk Makeup", product:"Matte Bronzer", shade:"Baked", price:"$28", hex:"#B07A40" }, { brand:"Milk Makeup", product:"Matte Bronzer", shade:"Baked II", price:"$28", hex:"#B07A40" }], [S]: [{ brand:"Tom Ford", product:"Soleil Glow", shade:"Gold Dust", price:"$58", hex:"#A07038" }, { brand:"Pat McGrath", product:"Soleil Glow", shade:"Gold Dust II", price:"$58", hex:"#A07038" }] },
  nails: { [B]: [{ brand:"e.l.f.", product:"Nail Polish", shade:"Golden Glow", price:"$4", hex:"#FFD700" }, { brand:"NYX", product:"Nail Polish", shade:"Golden Glow II", price:"$4", hex:"#FFD700" }], [V]: [{ brand:"Glossier", product:"Gel Cream", shade:"Fête", price:"$14", hex:"#FF9F43" }, { brand:"Kosas", product:"Gel Cream", shade:"Fête II", price:"$14", hex:"#FF9F43" }], [S]: [{ brand:"Tom Ford", product:"Nail Lacquer", shade:"Coral Sand", price:"$37", hex:"#E17055" }, { brand:"Pat McGrath", product:"Nail Lacquer", shade:"Coral Sand II", price:"$37", hex:"#E17055" }] },
},
"Light Spring": {
  foundation: { [B]: [{ brand:"L'Oréal", product:"True Match", shade:"W2 Light Ivory", price:"$12", hex:"#F0D5B8" }, { brand:"Maybelline", product:"True Match", shade:"W2 Light Ivory II", price:"$12", hex:"#F0D5B8" }], [V]: [{ brand:"Glossier", product:"Skin Tint", shade:"G5", price:"$28", hex:"#F0D5B8" }, { brand:"Kosas", product:"Skin Tint", shade:"G5 II", price:"$28", hex:"#F0D5B8" }], [S]: [{ brand:"Armani Beauty", product:"Luminous Silk", shade:"3.5", price:"$46", hex:"#F0D5B8" }, { brand:"Charlotte Tilbury", product:"Luminous Silk", shade:"3.5 II", price:"$46", hex:"#F0D5B8" }] },
  concealer: { [B]: [{ brand:"Maybelline", product:"Instant Age Rewind", shade:"Fair", price:"$10", hex:"#F5E0CC" }, { brand:"L'Oréal", product:"Instant Age Rewind", shade:"Fair II", price:"$10", hex:"#F5E0CC" }], [V]: [{ brand:"Too Faced", product:"Born This Way", shade:"Swan", price:"$24", hex:"#F5E0CC" }, { brand:"Too Faced", product:"Born This Way", shade:"Swan II", price:"$24", hex:"#F5E0CC" }], [S]: [{ brand:"NARS", product:"Radiant Creamy", shade:"Chantilly", price:"$32", hex:"#F5E0CC" }, { brand:"Dior Beauty", product:"Radiant Creamy", shade:"Chantilly II", price:"$32", hex:"#F5E0CC" }] },
  lips: { [B]: [{ brand:"NYX", product:"Butter Gloss", shade:"Crème Brûlée", price:"$6", hex:"#FFB6C1" }, { brand:"e.l.f.", product:"Butter Gloss", shade:"Crème Brûlée II", price:"$6", hex:"#FFB6C1" }], [V]: [{ brand:"Rare Beauty", product:"Kind Words", shade:"Worthy", price:"$20", hex:"#F08080" }, { brand:"Fenty Beauty", product:"Kind Words", shade:"Worthy II", price:"$20", hex:"#F08080" }], [S]: [{ brand:"Charlotte Tilbury", product:"Pillow Talk", shade:"Original", price:"$35", hex:"#F7CAC9" }, { brand:"Charlotte Tilbury", product:"Pillow Talk", shade:"Original II", price:"$35", hex:"#F7CAC9" }] },
  lipLiner: { [B]: [{ brand:"e.l.f.", product:"Lip Liner", shade:"Blush", price:"$3", hex:"#D4A09A" , pairsWith:"Complementary Lipstick" }, { brand:"NYX", product:"Lip Liner", shade:"Blush II", price:"$3", hex:"#D4A09A" }], [V]: [{ brand:"Patrick Ta", product:"Precision Liner", shade:"She's Gentle", price:"$24", hex:"#C49088" }, { brand:"Patrick Ta", product:"Precision Liner", shade:"She's Gentle II", price:"$24", hex:"#C49088" }], [S]: [{ brand:"Charlotte Tilbury", product:"Lip Cheat", shade:"Pillow Talk", price:"$25", hex:"#B88080" }, { brand:"Charlotte Tilbury", product:"Lip Cheat", shade:"Pillow Talk II", price:"$25", hex:"#B88080" }] },
  blush: { [B]: [{ brand:"Milani", product:"Baked Blush", shade:"Dolce Pink", price:"$9", hex:"#FFDAB9" }, { brand:"Milani", product:"Baked Blush", shade:"Dolce Pink II", price:"$9", hex:"#FFDAB9" }], [V]: [{ brand:"Glossier", product:"Cloud Paint", shade:"Puff", price:"$20", hex:"#FFB7A5" }, { brand:"Kosas", product:"Cloud Paint", shade:"Puff II", price:"$20", hex:"#FFB7A5" }], [S]: [{ brand:"NARS", product:"Blush", shade:"Sex Appeal", price:"$38", hex:"#FFD1DC" }, { brand:"Dior Beauty", product:"Blush", shade:"Sex Appeal II", price:"$38", hex:"#FFD1DC" }] },
  eyes: { [B]: [{ brand:"ColourPop", product:"Super Shock", shade:"Frog", price:"$6", hex:"#F3E5AB" }, { brand:"ColourPop", product:"Super Shock", shade:"Frog II", price:"$6", hex:"#F3E5AB" }], [V]: [{ brand:"Urban Decay", product:"Moondust", shade:"Space Cowboy", price:"$22", hex:"#C4B29A" }, { brand:"Urban Decay", product:"Moondust", shade:"Space Cowboy II", price:"$22", hex:"#C4B29A" }], [S]: [{ brand:"Tom Ford", product:"Quad", shade:"Nude Dip", price:"$90", hex:"#FFDAB9" }, { brand:"Pat McGrath", product:"Quad", shade:"Nude Dip II", price:"$90", hex:"#FFDAB9" }] },
  bronzer: { [B]: [{ brand:"Wet n Wild", product:"Color Icon", shade:"Reserve Your Cabana", price:"$5", hex:"#E8C8A0" }, { brand:"Wet n Wild", product:"Color Icon", shade:"Reserve Your Cabana II", price:"$5", hex:"#E8C8A0" }], [V]: [{ brand:"Milk Makeup", product:"Matte Bronzer", shade:"Light", price:"$28", hex:"#D0AA80" }, { brand:"Milk Makeup", product:"Matte Bronzer", shade:"Light II", price:"$28", hex:"#D0AA80" }], [S]: [{ brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Fair", price:"$49", hex:"#C49A70" }, { brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Fair II", price:"$49", hex:"#C49A70" }] },
  nails: { [B]: [{ brand:"e.l.f.", product:"Nail Polish", shade:"Petal Pink", price:"$4", hex:"#FFB6C1" }, { brand:"NYX", product:"Nail Polish", shade:"Petal Pink II", price:"$4", hex:"#FFB6C1" }], [V]: [{ brand:"Glossier", product:"Gel Cream", shade:"Hollyberry", price:"$14", hex:"#F08080" }, { brand:"Kosas", product:"Gel Cream", shade:"Hollyberry II", price:"$14", hex:"#F08080" }], [S]: [{ brand:"Tom Ford", product:"Nail Lacquer", shade:"Pink Crush", price:"$37", hex:"#E8C4A8" }, { brand:"Pat McGrath", product:"Nail Lacquer", shade:"Pink Crush II", price:"$37", hex:"#E8C4A8" }] },
},
"Soft Summer": {
  foundation: { [B]: [{ brand:"L'Oréal", product:"True Match", shade:"C3 Creamy Natural", price:"$12", hex:"#D5B5A0" }, { brand:"Maybelline", product:"True Match", shade:"C3 Creamy Natural II", price:"$12", hex:"#D5B5A0" }], [V]: [{ brand:"Rare Beauty", product:"Liquid Touch", shade:"210C", price:"$29", hex:"#D5B5A0" }, { brand:"Fenty Beauty", product:"Liquid Touch", shade:"210C II", price:"$29", hex:"#D5B5A0" }], [S]: [{ brand:"Armani Beauty", product:"Luminous Silk", shade:"4.5", price:"$46", hex:"#D5B5A0" }, { brand:"Charlotte Tilbury", product:"Luminous Silk", shade:"4.5 II", price:"$46", hex:"#D5B5A0" }] },
  concealer: { [B]: [{ brand:"Maybelline", product:"Instant Age Rewind", shade:"Neutralizer", price:"$10", hex:"#E0C8B8" }, { brand:"L'Oréal", product:"Instant Age Rewind", shade:"Neutralizer II", price:"$10", hex:"#E0C8B8" }], [V]: [{ brand:"Too Faced", product:"Born This Way", shade:"Natural Beige", price:"$24", hex:"#E0C8B8" }, { brand:"Too Faced", product:"Born This Way", shade:"Natural Beige II", price:"$24", hex:"#E0C8B8" }], [S]: [{ brand:"NARS", product:"Radiant Creamy", shade:"Custard", price:"$32", hex:"#E0C8B8" }, { brand:"Dior Beauty", product:"Radiant Creamy", shade:"Custard II", price:"$32", hex:"#E0C8B8" }] },
  lips: { [B]: [{ brand:"NYX", product:"Lip Lingerie", shade:"Embellishment", price:"$8", hex:"#C9929D" }, { brand:"e.l.f.", product:"Lip Lingerie", shade:"Embellishment II", price:"$8", hex:"#C9929D" }], [V]: [{ brand:"Rare Beauty", product:"Kind Words", shade:"Humble", price:"$20", hex:"#C08090" }, { brand:"Fenty Beauty", product:"Kind Words", shade:"Humble II", price:"$20", hex:"#C08090" }], [S]: [{ brand:"Charlotte Tilbury", product:"Matte Revolution", shade:"Pillow Talk", price:"$35", hex:"#B8908A" }, { brand:"Charlotte Tilbury", product:"Matte Revolution", shade:"Pillow Talk II", price:"$35", hex:"#B8908A" }] },
  lipLiner: { [B]: [{ brand:"NYX", product:"Suede Matte", shade:"Lavender & Lace", price:"$5", hex:"#A08888" , pairsWith:"Complementary Lipstick" }, { brand:"e.l.f.", product:"Suede Matte", shade:"Lavender & Lace II", price:"$5", hex:"#A08888" }], [V]: [{ brand:"Patrick Ta", product:"Precision Liner", shade:"She's Balanced", price:"$24", hex:"#9A7880" }, { brand:"Patrick Ta", product:"Precision Liner", shade:"She's Balanced II", price:"$24", hex:"#9A7880" }], [S]: [{ brand:"MAC", product:"Lip Pencil", shade:"Soar", price:"$23", hex:"#A07078" }, { brand:"MAC", product:"Lip Pencil", shade:"Soar II", price:"$23", hex:"#A07078" }] },
  blush: { [B]: [{ brand:"Milani", product:"Baked Blush", shade:"Rosa Romantica", price:"$9", hex:"#D4A0B0" }, { brand:"Milani", product:"Baked Blush", shade:"Rosa Romantica II", price:"$9", hex:"#D4A0B0" }], [V]: [{ brand:"Glossier", product:"Cloud Paint", shade:"Haze", price:"$20", hex:"#CFAEB5" }, { brand:"Kosas", product:"Cloud Paint", shade:"Haze II", price:"$20", hex:"#CFAEB5" }], [S]: [{ brand:"NARS", product:"Blush", shade:"Douceur", price:"$38", hex:"#CCADA0" }, { brand:"Dior Beauty", product:"Blush", shade:"Douceur II", price:"$38", hex:"#CCADA0" }] },
  eyes: { [B]: [{ brand:"Wet n Wild", product:"Color Icon", shade:"Walking on Eggshells", price:"$5", hex:"#B0A0B0" }, { brand:"Wet n Wild", product:"Color Icon", shade:"Walking on Eggshells II", price:"$5", hex:"#B0A0B0" }], [V]: [{ brand:"Urban Decay", product:"24/7 Shadow", shade:"Fog", price:"$22", hex:"#9B9EA3" }, { brand:"Urban Decay", product:"24/7 Shadow", shade:"Fog II", price:"$22", hex:"#9B9EA3" }], [S]: [{ brand:"Tom Ford", product:"Quad", shade:"Orchid Haze", price:"$90", hex:"#8B7B8B" }, { brand:"Pat McGrath", product:"Quad", shade:"Orchid Haze II", price:"$90", hex:"#8B7B8B" }] },
  bronzer: { [B]: [{ brand:"e.l.f.", product:"Putty Bronzer", shade:"Feelin' Shady", price:"$7", hex:"#B8A088" }, { brand:"NYX", product:"Putty Bronzer", shade:"Feelin' Shady II", price:"$7", hex:"#B8A088" }], [V]: [{ brand:"Milk Makeup", product:"Matte Bronzer", shade:"Baked", price:"$28", hex:"#A89078" }, { brand:"Milk Makeup", product:"Matte Bronzer", shade:"Baked II", price:"$28", hex:"#A89078" }], [S]: [{ brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Fair/Medium", price:"$49", hex:"#988068" }, { brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Fair/Medium II", price:"$49", hex:"#988068" }] },
  nails: { [B]: [{ brand:"e.l.f.", product:"Nail Polish", shade:"Dusty Rose", price:"$4", hex:"#C9929D" }, { brand:"NYX", product:"Nail Polish", shade:"Dusty Rose II", price:"$4", hex:"#C9929D" }], [V]: [{ brand:"Glossier", product:"Gel Cream", shade:"Lavender", price:"$14", hex:"#B0A0B0" }, { brand:"Kosas", product:"Gel Cream", shade:"Lavender II", price:"$14", hex:"#B0A0B0" }], [S]: [{ brand:"Tom Ford", product:"Nail Lacquer", shade:"Mink Brûlée", price:"$37", hex:"#A09088" }, { brand:"Pat McGrath", product:"Nail Lacquer", shade:"Mink Brûlée II", price:"$37", hex:"#A09088" }] },
},
"True Summer": {
  foundation: { [B]: [{ brand:"Maybelline", product:"Fit Me Matte", shade:"120 Classic Ivory", price:"$9", hex:"#E0C4B5" }, { brand:"L'Oréal", product:"Fit Me Matte", shade:"120 Classic Ivory II", price:"$9", hex:"#E0C4B5" }], [V]: [{ brand:"Rare Beauty", product:"Liquid Touch", shade:"170C", price:"$29", hex:"#E0C4B5" }, { brand:"Fenty Beauty", product:"Liquid Touch", shade:"170C II", price:"$29", hex:"#E0C4B5" }], [S]: [{ brand:"Armani Beauty", product:"Luminous Silk", shade:"4", price:"$46", hex:"#E0C4B5" }, { brand:"Charlotte Tilbury", product:"Luminous Silk", shade:"4 II", price:"$46", hex:"#E0C4B5" }] },
  concealer: { [B]: [{ brand:"e.l.f.", product:"Hydrating Camo", shade:"Light Ivory", price:"$7", hex:"#EAD4C5" }, { brand:"NYX", product:"Hydrating Camo", shade:"Light Ivory II", price:"$7", hex:"#EAD4C5" }], [V]: [{ brand:"Too Faced", product:"Born This Way", shade:"Porcelain", price:"$24", hex:"#EAD4C5" }, { brand:"Too Faced", product:"Born This Way", shade:"Porcelain II", price:"$24", hex:"#EAD4C5" }], [S]: [{ brand:"Pat McGrath", product:"Sublime Perfection", shade:"L5", price:"$38", hex:"#EAD4C5" }, { brand:"Pat McGrath", product:"Sublime Perfection", shade:"L5 II", price:"$38", hex:"#EAD4C5" }] },
  lips: { [B]: [{ brand:"NYX", product:"Butter Gloss", shade:"Angel Food Cake", price:"$6", hex:"#DB7093" }, { brand:"e.l.f.", product:"Butter Gloss", shade:"Angel Food Cake II", price:"$6", hex:"#DB7093" }], [V]: [{ brand:"Rare Beauty", product:"Soft Pinch Liquid", shade:"Happy", price:"$22", hex:"#C23B73" }, { brand:"Fenty Beauty", product:"Soft Pinch Liquid", shade:"Happy II", price:"$22", hex:"#C23B73" }], [S]: [{ brand:"Charlotte Tilbury", product:"Matte Revolution", shade:"Very Victoria", price:"$35", hex:"#8B3A62" }, { brand:"Charlotte Tilbury", product:"Matte Revolution", shade:"Very Victoria II", price:"$35", hex:"#8B3A62" }] },
  lipLiner: { [B]: [{ brand:"NYX", product:"Suede Matte", shade:"Tea & Cookies", price:"$5", hex:"#A07080" , pairsWith:"Complementary Lipstick" }, { brand:"e.l.f.", product:"Suede Matte", shade:"Tea & Cookies II", price:"$5", hex:"#A07080" }], [V]: [{ brand:"Patrick Ta", product:"Precision Liner", shade:"She's Poised", price:"$24", hex:"#904868" }, { brand:"Patrick Ta", product:"Precision Liner", shade:"She's Poised II", price:"$24", hex:"#904868" }], [S]: [{ brand:"MAC", product:"Lip Pencil", shade:"Whirl", price:"$23", hex:"#885060" }, { brand:"MAC", product:"Lip Pencil", shade:"Whirl II", price:"$23", hex:"#885060" }] },
  blush: { [B]: [{ brand:"Milani", product:"Baked Blush", shade:"Bella Rosa", price:"$9", hex:"#E8A0B4" }, { brand:"Milani", product:"Baked Blush", shade:"Bella Rosa II", price:"$9", hex:"#E8A0B4" }], [V]: [{ brand:"Rare Beauty", product:"Soft Pinch", shade:"Bliss", price:"$23", hex:"#C8788C" }, { brand:"Fenty Beauty", product:"Soft Pinch", shade:"Bliss II", price:"$23", hex:"#C8788C" }], [S]: [{ brand:"NARS", product:"Blush", shade:"Impassioned", price:"$38", hex:"#C08090" }, { brand:"Dior Beauty", product:"Blush", shade:"Impassioned II", price:"$38", hex:"#C08090" }] },
  eyes: { [B]: [{ brand:"ColourPop", product:"Super Shock", shade:"Amaze", price:"$6", hex:"#9A8B80" }, { brand:"ColourPop", product:"Super Shock", shade:"Amaze II", price:"$6", hex:"#9A8B80" }], [V]: [{ brand:"Urban Decay", product:"24/7 Shadow", shade:"Tease", price:"$22", hex:"#6A7B8B" }, { brand:"Urban Decay", product:"24/7 Shadow", shade:"Tease II", price:"$22", hex:"#6A7B8B" }], [S]: [{ brand:"Tom Ford", product:"Quad", shade:"Seductive Rose", price:"$90", hex:"#C4B0D4" }, { brand:"Pat McGrath", product:"Quad", shade:"Seductive Rose II", price:"$90", hex:"#C4B0D4" }] },
  bronzer: { [B]: [{ brand:"Wet n Wild", product:"Color Icon", shade:"Dulce De Leche", price:"$5", hex:"#B09888" }, { brand:"Wet n Wild", product:"Color Icon", shade:"Dulce De Leche II", price:"$5", hex:"#B09888" }], [V]: [{ brand:"Milk Makeup", product:"Matte Bronzer", shade:"Light", price:"$28", hex:"#A08878" }, { brand:"Milk Makeup", product:"Matte Bronzer", shade:"Light II", price:"$28", hex:"#A08878" }], [S]: [{ brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Light/Medium", price:"$49", hex:"#907868" }, { brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Light/Medium II", price:"$49", hex:"#907868" }] },
  nails: { [B]: [{ brand:"e.l.f.", product:"Nail Polish", shade:"Berry Nice", price:"$4", hex:"#C71585" }, { brand:"NYX", product:"Nail Polish", shade:"Berry Nice II", price:"$4", hex:"#C71585" }], [V]: [{ brand:"Glossier", product:"Gel Cream", shade:"Petal", price:"$14", hex:"#DB7093" }, { brand:"Kosas", product:"Gel Cream", shade:"Petal II", price:"$14", hex:"#DB7093" }], [S]: [{ brand:"Tom Ford", product:"Nail Lacquer", shade:"Indian Pink", price:"$37", hex:"#8B3A62" }, { brand:"Pat McGrath", product:"Nail Lacquer", shade:"Indian Pink II", price:"$37", hex:"#8B3A62" }] },
},
"Light Summer": {
  foundation: { [B]: [{ brand:"L'Oréal", product:"True Match", shade:"C1 Alabaster", price:"$12", hex:"#F0DAD0" }, { brand:"Maybelline", product:"True Match", shade:"C1 Alabaster II", price:"$12", hex:"#F0DAD0" }], [V]: [{ brand:"Glossier", product:"Skin Tint", shade:"G4", price:"$28", hex:"#F0DAD0" }, { brand:"Kosas", product:"Skin Tint", shade:"G4 II", price:"$28", hex:"#F0DAD0" }], [S]: [{ brand:"Armani Beauty", product:"Luminous Silk", shade:"2", price:"$46", hex:"#F0DAD0" }, { brand:"Charlotte Tilbury", product:"Luminous Silk", shade:"2 II", price:"$46", hex:"#F0DAD0" }] },
  concealer: { [B]: [{ brand:"Maybelline", product:"Instant Age Rewind", shade:"Brightener", price:"$10", hex:"#F8E8DC" }, { brand:"L'Oréal", product:"Instant Age Rewind", shade:"Brightener II", price:"$10", hex:"#F8E8DC" }], [V]: [{ brand:"Too Faced", product:"Born This Way", shade:"Cloud", price:"$24", hex:"#F8E8DC" }, { brand:"Too Faced", product:"Born This Way", shade:"Cloud II", price:"$24", hex:"#F8E8DC" }], [S]: [{ brand:"NARS", product:"Radiant Creamy", shade:"Vanilla", price:"$32", hex:"#F8E8DC" }, { brand:"Dior Beauty", product:"Radiant Creamy", shade:"Vanilla II", price:"$32", hex:"#F8E8DC" }] },
  lips: { [B]: [{ brand:"NYX", product:"Butter Gloss", shade:"Tiramisu", price:"$6", hex:"#FFB6C1" }, { brand:"e.l.f.", product:"Butter Gloss", shade:"Tiramisu II", price:"$6", hex:"#FFB6C1" }], [V]: [{ brand:"Rare Beauty", product:"Kind Words", shade:"Lovely", price:"$20", hex:"#F0C0D0" }, { brand:"Fenty Beauty", product:"Kind Words", shade:"Lovely II", price:"$20", hex:"#F0C0D0" }], [S]: [{ brand:"Charlotte Tilbury", product:"Lip Lustre", shade:"Sweet Stiletto", price:"$35", hex:"#E8B4D0" }, { brand:"Charlotte Tilbury", product:"Lip Lustre", shade:"Sweet Stiletto II", price:"$35", hex:"#E8B4D0" }] },
  lipLiner: { [B]: [{ brand:"e.l.f.", product:"Lip Liner", shade:"Pink", price:"$3", hex:"#D0A0B0" , pairsWith:"Complementary Lipstick" }, { brand:"NYX", product:"Lip Liner", shade:"Pink II", price:"$3", hex:"#D0A0B0" }], [V]: [{ brand:"Patrick Ta", product:"Precision Liner", shade:"She's Delicate", price:"$24", hex:"#C090A0" }, { brand:"Patrick Ta", product:"Precision Liner", shade:"She's Delicate II", price:"$24", hex:"#C090A0" }], [S]: [{ brand:"Charlotte Tilbury", product:"Lip Cheat", shade:"Pink Venus", price:"$25", hex:"#B08890" }, { brand:"Charlotte Tilbury", product:"Lip Cheat", shade:"Pink Venus II", price:"$25", hex:"#B08890" }] },
  blush: { [B]: [{ brand:"Milani", product:"Baked Blush", shade:"Dolce Pink", price:"$9", hex:"#F0C0D0" }, { brand:"Milani", product:"Baked Blush", shade:"Dolce Pink II", price:"$9", hex:"#F0C0D0" }], [V]: [{ brand:"Glossier", product:"Cloud Paint", shade:"Puff", price:"$20", hex:"#E0BBE4" }, { brand:"Kosas", product:"Cloud Paint", shade:"Puff II", price:"$20", hex:"#E0BBE4" }], [S]: [{ brand:"NARS", product:"Blush", shade:"Sex Appeal", price:"$38", hex:"#F7CAC9" }, { brand:"Dior Beauty", product:"Blush", shade:"Sex Appeal II", price:"$38", hex:"#F7CAC9" }] },
  eyes: { [B]: [{ brand:"Wet n Wild", product:"Color Icon", shade:"Petalette", price:"$5", hex:"#B0C4DE" }, { brand:"Wet n Wild", product:"Color Icon", shade:"Petalette II", price:"$5", hex:"#B0C4DE" }], [V]: [{ brand:"Urban Decay", product:"Moondust", shade:"Cosmic", price:"$22", hex:"#E0BBE4" }, { brand:"Urban Decay", product:"Moondust", shade:"Cosmic II", price:"$22", hex:"#E0BBE4" }], [S]: [{ brand:"Tom Ford", product:"Quad", shade:"Silvered Topaz", price:"$90", hex:"#C8C8D0" }, { brand:"Pat McGrath", product:"Quad", shade:"Silvered Topaz II", price:"$90", hex:"#C8C8D0" }] },
  bronzer: { [B]: [{ brand:"e.l.f.", product:"Putty Bronzer", shade:"Tan Lines", price:"$7", hex:"#D4B8A0" }, { brand:"NYX", product:"Putty Bronzer", shade:"Tan Lines II", price:"$7", hex:"#D4B8A0" }], [V]: [{ brand:"Milk Makeup", product:"Matte Bronzer", shade:"Light", price:"$28", hex:"#C4A890" }, { brand:"Milk Makeup", product:"Matte Bronzer", shade:"Light II", price:"$28", hex:"#C4A890" }], [S]: [{ brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Fair", price:"$49", hex:"#B49880" }, { brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Fair II", price:"$49", hex:"#B49880" }] },
  nails: { [B]: [{ brand:"e.l.f.", product:"Nail Polish", shade:"Light Lilac", price:"$4", hex:"#E0BBE4" }, { brand:"NYX", product:"Nail Polish", shade:"Light Lilac II", price:"$4", hex:"#E0BBE4" }], [V]: [{ brand:"Glossier", product:"Gel Cream", shade:"Iris", price:"$14", hex:"#B0C4DE" }, { brand:"Kosas", product:"Gel Cream", shade:"Iris II", price:"$14", hex:"#B0C4DE" }], [S]: [{ brand:"Tom Ford", product:"Nail Lacquer", shade:"Sugar Dune", price:"$37", hex:"#F7CAC9" }, { brand:"Pat McGrath", product:"Nail Lacquer", shade:"Sugar Dune II", price:"$37", hex:"#F7CAC9" }] },
},
"Soft Autumn": {
  foundation: { [B]: [{ brand:"L'Oréal", product:"True Match", shade:"W4.5 Fresh Beige", price:"$12", hex:"#CCAA88" }, { brand:"Maybelline", product:"True Match", shade:"W4.5 Fresh Beige II", price:"$12", hex:"#CCAA88" }], [V]: [{ brand:"Rare Beauty", product:"Liquid Touch", shade:"270W", price:"$29", hex:"#CCAA88" }, { brand:"Fenty Beauty", product:"Liquid Touch", shade:"270W II", price:"$29", hex:"#CCAA88" }], [S]: [{ brand:"Armani Beauty", product:"Luminous Silk", shade:"6.5", price:"$46", hex:"#CCAA88" }, { brand:"Charlotte Tilbury", product:"Luminous Silk", shade:"6.5 II", price:"$46", hex:"#CCAA88" }] },
  concealer: { [B]: [{ brand:"e.l.f.", product:"Hydrating Camo", shade:"Medium Warm", price:"$7", hex:"#DABB9A" }, { brand:"NYX", product:"Hydrating Camo", shade:"Medium Warm II", price:"$7", hex:"#DABB9A" }], [V]: [{ brand:"Milk Makeup", product:"Future Fluid", shade:"14", price:"$28", hex:"#DABB9A" }, { brand:"Milk Makeup", product:"Future Fluid", shade:"14 II", price:"$28", hex:"#DABB9A" }], [S]: [{ brand:"Pat McGrath", product:"Sublime Perfection", shade:"LM15", price:"$38", hex:"#DABB9A" }, { brand:"Pat McGrath", product:"Sublime Perfection", shade:"LM15 II", price:"$38", hex:"#DABB9A" }] },
  lips: { [B]: [{ brand:"NYX", product:"Lip Lingerie", shade:"Bedtime Flirt", price:"$8", hex:"#C4A882" }, { brand:"e.l.f.", product:"Lip Lingerie", shade:"Bedtime Flirt II", price:"$8", hex:"#C4A882" }], [V]: [{ brand:"Rare Beauty", product:"Kind Words", shade:"Humble", price:"$20", hex:"#C08060" }, { brand:"Fenty Beauty", product:"Kind Words", shade:"Humble II", price:"$20", hex:"#C08060" }], [S]: [{ brand:"Charlotte Tilbury", product:"Pillow Talk", shade:"Medium", price:"$35", hex:"#B8908A" }, { brand:"Charlotte Tilbury", product:"Pillow Talk", shade:"Medium II", price:"$35", hex:"#B8908A" }] },
  lipLiner: { [B]: [{ brand:"NYX", product:"Suede Matte", shade:"Soft-Spoken", price:"$5", hex:"#A08870" , pairsWith:"Complementary Lipstick" }, { brand:"e.l.f.", product:"Suede Matte", shade:"Soft-Spoken II", price:"$5", hex:"#A08870" }], [V]: [{ brand:"Patrick Ta", product:"Precision Liner", shade:"She's Subtle", price:"$24", hex:"#907858" }, { brand:"Patrick Ta", product:"Precision Liner", shade:"She's Subtle II", price:"$24", hex:"#907858" }], [S]: [{ brand:"MAC", product:"Lip Pencil", shade:"Stripdown", price:"$23", hex:"#886848" }, { brand:"MAC", product:"Lip Pencil", shade:"Stripdown II", price:"$23", hex:"#886848" }] },
  blush: { [B]: [{ brand:"Milani", product:"Baked Blush", shade:"Luminoso", price:"$9", hex:"#C4A090" }, { brand:"Milani", product:"Baked Blush", shade:"Luminoso II", price:"$9", hex:"#C4A090" }], [V]: [{ brand:"Glossier", product:"Cloud Paint", shade:"Dusk", price:"$20", hex:"#C8A898" }, { brand:"Kosas", product:"Cloud Paint", shade:"Dusk II", price:"$20", hex:"#C8A898" }], [S]: [{ brand:"NARS", product:"Blush", shade:"Madly", price:"$38", hex:"#C4B09A" }, { brand:"Dior Beauty", product:"Blush", shade:"Madly II", price:"$38", hex:"#C4B09A" }] },
  eyes: { [B]: [{ brand:"ColourPop", product:"Super Shock", shade:"Nillionaire", price:"$6", hex:"#A09080" }, { brand:"ColourPop", product:"Super Shock", shade:"Nillionaire II", price:"$6", hex:"#A09080" }], [V]: [{ brand:"Urban Decay", product:"24/7 Shadow", shade:"Roach", price:"$22", hex:"#8A9A6B" }, { brand:"Urban Decay", product:"24/7 Shadow", shade:"Roach II", price:"$22", hex:"#8A9A6B" }], [S]: [{ brand:"Tom Ford", product:"Quad", shade:"Cognac Sable", price:"$90", hex:"#8B6B50" }, { brand:"Pat McGrath", product:"Quad", shade:"Cognac Sable II", price:"$90", hex:"#8B6B50" }] },
  bronzer: { [B]: [{ brand:"Wet n Wild", product:"Color Icon", shade:"Ticket to Brazil", price:"$5", hex:"#B09068" }, { brand:"Wet n Wild", product:"Color Icon", shade:"Ticket to Brazil II", price:"$5", hex:"#B09068" }], [V]: [{ brand:"Milk Makeup", product:"Matte Bronzer", shade:"Baked", price:"$28", hex:"#A08058" }, { brand:"Milk Makeup", product:"Matte Bronzer", shade:"Baked II", price:"$28", hex:"#A08058" }], [S]: [{ brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Medium", price:"$49", hex:"#907048" }, { brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Medium II", price:"$49", hex:"#907048" }] },
  nails: { [B]: [{ brand:"e.l.f.", product:"Nail Polish", shade:"Taupe", price:"$4", hex:"#A09080" }, { brand:"NYX", product:"Nail Polish", shade:"Taupe II", price:"$4", hex:"#A09080" }], [V]: [{ brand:"Glossier", product:"Gel Cream", shade:"Cachet", price:"$14", hex:"#8A9A6B" }, { brand:"Kosas", product:"Gel Cream", shade:"Cachet II", price:"$14", hex:"#8A9A6B" }], [S]: [{ brand:"Tom Ford", product:"Nail Lacquer", shade:"Sable Smoke", price:"$37", hex:"#8B6B50" }, { brand:"Pat McGrath", product:"Nail Lacquer", shade:"Sable Smoke II", price:"$37", hex:"#8B6B50" }] },
},
"True Autumn": {
  foundation: { [B]: [{ brand:"Maybelline", product:"Fit Me Dewy", shade:"310 Sun Beige", price:"$9", hex:"#C49060" }, { brand:"L'Oréal", product:"Fit Me Dewy", shade:"310 Sun Beige II", price:"$9", hex:"#C49060" }], [V]: [{ brand:"Rare Beauty", product:"Liquid Touch", shade:"330W", price:"$29", hex:"#C49060" }, { brand:"Fenty Beauty", product:"Liquid Touch", shade:"330W II", price:"$29", hex:"#C49060" }], [S]: [{ brand:"Armani Beauty", product:"Luminous Silk", shade:"8", price:"$46", hex:"#C49060" }, { brand:"Charlotte Tilbury", product:"Luminous Silk", shade:"8 II", price:"$46", hex:"#C49060" }] },
  concealer: { [B]: [{ brand:"e.l.f.", product:"Hydrating Camo", shade:"Medium Golden", price:"$7", hex:"#D4A878" }, { brand:"NYX", product:"Hydrating Camo", shade:"Medium Golden II", price:"$7", hex:"#D4A878" }], [V]: [{ brand:"Too Faced", product:"Born This Way", shade:"Warm Sand", price:"$24", hex:"#D4A878" }, { brand:"Too Faced", product:"Born This Way", shade:"Warm Sand II", price:"$24", hex:"#D4A878" }], [S]: [{ brand:"NARS", product:"Radiant Creamy", shade:"Caramel", price:"$32", hex:"#D4A878" }, { brand:"Dior Beauty", product:"Radiant Creamy", shade:"Caramel II", price:"$32", hex:"#D4A878" }] },
  lips: { [B]: [{ brand:"NYX", product:"Lip Lingerie", shade:"Exotic", price:"$8", hex:"#CC6633" }, { brand:"e.l.f.", product:"Lip Lingerie", shade:"Exotic II", price:"$8", hex:"#CC6633" }], [V]: [{ brand:"Rare Beauty", product:"Soft Pinch Liquid", shade:"Inspire", price:"$22", hex:"#B04030" }, { brand:"Fenty Beauty", product:"Soft Pinch Liquid", shade:"Inspire II", price:"$22", hex:"#B04030" }], [S]: [{ brand:"Charlotte Tilbury", product:"Matte Revolution", shade:"Walk of No Shame", price:"$35", hex:"#8B3A2A" }, { brand:"Charlotte Tilbury", product:"Matte Revolution", shade:"Walk of No Shame II", price:"$35", hex:"#8B3A2A" }] },
  lipLiner: { [B]: [{ brand:"NYX", product:"Suede Matte", shade:"Leon", price:"$5", hex:"#8B5030" , pairsWith:"Complementary Lipstick" }, { brand:"e.l.f.", product:"Suede Matte", shade:"Leon II", price:"$5", hex:"#8B5030" }], [V]: [{ brand:"Patrick Ta", product:"Precision Liner", shade:"She's Bold", price:"$24", hex:"#7A4028" }, { brand:"Patrick Ta", product:"Precision Liner", shade:"She's Bold II", price:"$24", hex:"#7A4028" }], [S]: [{ brand:"MAC", product:"Lip Pencil", shade:"Chestnut", price:"$23", hex:"#6A3020" }, { brand:"MAC", product:"Lip Pencil", shade:"Chestnut II", price:"$23", hex:"#6A3020" }] },
  blush: { [B]: [{ brand:"Milani", product:"Baked Blush", shade:"Rose D'Oro", price:"$9", hex:"#CC6633" }, { brand:"Milani", product:"Baked Blush", shade:"Rose D'Oro II", price:"$9", hex:"#CC6633" }], [V]: [{ brand:"Rare Beauty", product:"Soft Pinch", shade:"Encourage", price:"$23", hex:"#CD853F" }, { brand:"Fenty Beauty", product:"Soft Pinch", shade:"Encourage II", price:"$23", hex:"#CD853F" }], [S]: [{ brand:"NARS", product:"Blush", shade:"Taj Mahal", price:"$38", hex:"#C08050" }, { brand:"Dior Beauty", product:"Blush", shade:"Taj Mahal II", price:"$38", hex:"#C08050" }] },
  eyes: { [B]: [{ brand:"ColourPop", product:"Super Shock", shade:"Bae", price:"$6", hex:"#B8860B" }, { brand:"ColourPop", product:"Super Shock", shade:"Bae II", price:"$6", hex:"#B8860B" }], [V]: [{ brand:"Urban Decay", product:"24/7 Shadow", shade:"Smog", price:"$22", hex:"#8B5A2B" }, { brand:"Urban Decay", product:"24/7 Shadow", shade:"Smog II", price:"$22", hex:"#8B5A2B" }], [S]: [{ brand:"Tom Ford", product:"Quad", shade:"Leopard Sun", price:"$90", hex:"#B87333" }, { brand:"Pat McGrath", product:"Quad", shade:"Leopard Sun II", price:"$90", hex:"#B87333" }] },
  bronzer: { [B]: [{ brand:"Wet n Wild", product:"Color Icon", shade:"Ticket to Brazil", price:"$5", hex:"#A07840" }, { brand:"Wet n Wild", product:"Color Icon", shade:"Ticket to Brazil II", price:"$5", hex:"#A07840" }], [V]: [{ brand:"Milk Makeup", product:"Matte Bronzer", shade:"Baked", price:"$28", hex:"#906830" }, { brand:"Milk Makeup", product:"Matte Bronzer", shade:"Baked II", price:"$28", hex:"#906830" }], [S]: [{ brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Medium/Dark", price:"$49", hex:"#805828" }, { brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Medium/Dark II", price:"$49", hex:"#805828" }] },
  nails: { [B]: [{ brand:"e.l.f.", product:"Nail Polish", shade:"Terracotta", price:"$4", hex:"#CC6633" }, { brand:"NYX", product:"Nail Polish", shade:"Terracotta II", price:"$4", hex:"#CC6633" }], [V]: [{ brand:"Glossier", product:"Gel Cream", shade:"Cachet", price:"$14", hex:"#A0522D" }, { brand:"Kosas", product:"Gel Cream", shade:"Cachet II", price:"$14", hex:"#A0522D" }], [S]: [{ brand:"Tom Ford", product:"Nail Lacquer", shade:"Burnished Rouge", price:"$37", hex:"#8B4513" }, { brand:"Pat McGrath", product:"Nail Lacquer", shade:"Burnished Rouge II", price:"$37", hex:"#8B4513" }] },
},
"Dark Autumn": {
  foundation: { [B]: [{ brand:"L'Oréal", product:"True Match", shade:"W7 Caramel Beige", price:"$12", hex:"#A07848" }, { brand:"Maybelline", product:"True Match", shade:"W7 Caramel Beige II", price:"$12", hex:"#A07848" }], [V]: [{ brand:"Rare Beauty", product:"Liquid Touch", shade:"410W", price:"$29", hex:"#A07848" }, { brand:"Fenty Beauty", product:"Liquid Touch", shade:"410W II", price:"$29", hex:"#A07848" }], [S]: [{ brand:"Armani Beauty", product:"Luminous Silk", shade:"10", price:"$46", hex:"#A07848" }, { brand:"Charlotte Tilbury", product:"Luminous Silk", shade:"10 II", price:"$46", hex:"#A07848" }] },
  concealer: { [B]: [{ brand:"Maybelline", product:"Instant Age Rewind", shade:"Caramel", price:"$10", hex:"#B49060" }, { brand:"L'Oréal", product:"Instant Age Rewind", shade:"Caramel II", price:"$10", hex:"#B49060" }], [V]: [{ brand:"Too Faced", product:"Born This Way", shade:"Toffee", price:"$24", hex:"#B49060" }, { brand:"Too Faced", product:"Born This Way", shade:"Toffee II", price:"$24", hex:"#B49060" }], [S]: [{ brand:"Pat McGrath", product:"Sublime Perfection", shade:"M18", price:"$38", hex:"#B49060" }, { brand:"Pat McGrath", product:"Sublime Perfection", shade:"M18 II", price:"$38", hex:"#B49060" }] },
  lips: { [B]: [{ brand:"NYX", product:"Lip Lingerie", shade:"Beauty Mark", price:"$8", hex:"#800020" }, { brand:"e.l.f.", product:"Lip Lingerie", shade:"Beauty Mark II", price:"$8", hex:"#800020" }], [V]: [{ brand:"Rare Beauty", product:"Soft Pinch Liquid", shade:"Devotion", price:"$22", hex:"#6B1A2A" }, { brand:"Fenty Beauty", product:"Soft Pinch Liquid", shade:"Devotion II", price:"$22", hex:"#6B1A2A" }], [S]: [{ brand:"Charlotte Tilbury", product:"Matte Revolution", shade:"Legendary Queen", price:"$35", hex:"#722F37" }, { brand:"Charlotte Tilbury", product:"Matte Revolution", shade:"Legendary Queen II", price:"$35", hex:"#722F37" }] },
  lipLiner: { [B]: [{ brand:"NYX", product:"Suede Matte", shade:"Cold Brew", price:"$5", hex:"#5A2020" , pairsWith:"Complementary Lipstick" }, { brand:"e.l.f.", product:"Suede Matte", shade:"Cold Brew II", price:"$5", hex:"#5A2020" }], [V]: [{ brand:"Patrick Ta", product:"Precision Liner", shade:"She's Fierce", price:"$24", hex:"#4A1818" }, { brand:"Patrick Ta", product:"Precision Liner", shade:"She's Fierce II", price:"$24", hex:"#4A1818" }], [S]: [{ brand:"MAC", product:"Lip Pencil", shade:"Nightmoth", price:"$23", hex:"#3A1010" }, { brand:"MAC", product:"Lip Pencil", shade:"Nightmoth II", price:"$23", hex:"#3A1010" }] },
  blush: { [B]: [{ brand:"Milani", product:"Baked Blush", shade:"Red Vino", price:"$9", hex:"#B07050" }, { brand:"Milani", product:"Baked Blush", shade:"Red Vino II", price:"$9", hex:"#B07050" }], [V]: [{ brand:"Rare Beauty", product:"Soft Pinch", shade:"Encourage", price:"$23", hex:"#A0603A" }, { brand:"Fenty Beauty", product:"Soft Pinch", shade:"Encourage II", price:"$23", hex:"#A0603A" }], [S]: [{ brand:"NARS", product:"Blush", shade:"Exhibit A", price:"$38", hex:"#A06060" }, { brand:"Dior Beauty", product:"Blush", shade:"Exhibit A II", price:"$38", hex:"#A06060" }] },
  eyes: { [B]: [{ brand:"ColourPop", product:"Super Shock", shade:"Mittens", price:"$6", hex:"#6B4226" }, { brand:"ColourPop", product:"Super Shock", shade:"Mittens II", price:"$6", hex:"#6B4226" }], [V]: [{ brand:"Urban Decay", product:"24/7 Shadow", shade:"Mildew", price:"$22", hex:"#2E4A2E" }, { brand:"Urban Decay", product:"24/7 Shadow", shade:"Mildew II", price:"$22", hex:"#2E4A2E" }], [S]: [{ brand:"Tom Ford", product:"Quad", shade:"Body Heat", price:"$90", hex:"#8B7220" }, { brand:"Pat McGrath", product:"Quad", shade:"Body Heat II", price:"$90", hex:"#8B7220" }] },
  bronzer: { [B]: [{ brand:"Wet n Wild", product:"Color Icon", shade:"What Shady Beaches", price:"$5", hex:"#906838" }, { brand:"Wet n Wild", product:"Color Icon", shade:"What Shady Beaches II", price:"$5", hex:"#906838" }], [V]: [{ brand:"Milk Makeup", product:"Matte Bronzer", shade:"Toasted", price:"$28", hex:"#805828" }, { brand:"Milk Makeup", product:"Matte Bronzer", shade:"Toasted II", price:"$28", hex:"#805828" }], [S]: [{ brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Dark", price:"$49", hex:"#704820" }, { brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Dark II", price:"$49", hex:"#704820" }] },
  nails: { [B]: [{ brand:"e.l.f.", product:"Nail Polish", shade:"Dark Plum", price:"$4", hex:"#800020" }, { brand:"NYX", product:"Nail Polish", shade:"Dark Plum II", price:"$4", hex:"#800020" }], [V]: [{ brand:"Glossier", product:"Gel Cream", shade:"Thorn", price:"$14", hex:"#6B1A2A" }, { brand:"Kosas", product:"Gel Cream", shade:"Thorn II", price:"$14", hex:"#6B1A2A" }], [S]: [{ brand:"Tom Ford", product:"Nail Lacquer", shade:"Black Cherry", price:"$37", hex:"#4A0E1F" }, { brand:"Pat McGrath", product:"Nail Lacquer", shade:"Black Cherry II", price:"$37", hex:"#4A0E1F" }] },
},
"Dark Winter": {
  foundation: { [B]: [{ brand:"Maybelline", product:"Fit Me Matte", shade:"355 Coconut", price:"$9", hex:"#956848" }, { brand:"L'Oréal", product:"Fit Me Matte", shade:"355 Coconut II", price:"$9", hex:"#956848" }], [V]: [{ brand:"Rare Beauty", product:"Liquid Touch", shade:"440C", price:"$29", hex:"#956848" }, { brand:"Fenty Beauty", product:"Liquid Touch", shade:"440C II", price:"$29", hex:"#956848" }], [S]: [{ brand:"Armani Beauty", product:"Luminous Silk", shade:"11.5", price:"$46", hex:"#956848" }, { brand:"Charlotte Tilbury", product:"Luminous Silk", shade:"11.5 II", price:"$46", hex:"#956848" }] },
  concealer: { [B]: [{ brand:"e.l.f.", product:"Hydrating Camo", shade:"Rich Chocolate", price:"$7", hex:"#A88060" }, { brand:"NYX", product:"Hydrating Camo", shade:"Rich Chocolate II", price:"$7", hex:"#A88060" }], [V]: [{ brand:"Too Faced", product:"Born This Way", shade:"Chai", price:"$24", hex:"#A88060" }, { brand:"Too Faced", product:"Born This Way", shade:"Chai II", price:"$24", hex:"#A88060" }], [S]: [{ brand:"NARS", product:"Radiant Creamy", shade:"Amande", price:"$32", hex:"#A88060" }, { brand:"Dior Beauty", product:"Radiant Creamy", shade:"Amande II", price:"$32", hex:"#A88060" }] },
  lips: { [B]: [{ brand:"NYX", product:"Lip Lingerie", shade:"Exotic", price:"$8", hex:"#6B1A3A" }, { brand:"e.l.f.", product:"Lip Lingerie", shade:"Exotic II", price:"$8", hex:"#6B1A3A" }], [V]: [{ brand:"Rare Beauty", product:"Soft Pinch Liquid", shade:"Inspire", price:"$22", hex:"#800020" }, { brand:"Fenty Beauty", product:"Soft Pinch Liquid", shade:"Inspire II", price:"$22", hex:"#800020" }], [S]: [{ brand:"Charlotte Tilbury", product:"Matte Revolution", shade:"Scarlet Spell", price:"$35", hex:"#CC0000" }, { brand:"Charlotte Tilbury", product:"Matte Revolution", shade:"Scarlet Spell II", price:"$35", hex:"#CC0000" }] },
  lipLiner: { [B]: [{ brand:"NYX", product:"Suede Matte", shade:"Vintage", price:"$5", hex:"#5A1030" , pairsWith:"Complementary Lipstick" }, { brand:"e.l.f.", product:"Suede Matte", shade:"Vintage II", price:"$5", hex:"#5A1030" }], [V]: [{ brand:"Patrick Ta", product:"Precision Liner", shade:"She's Dangerous", price:"$24", hex:"#4A0828" }, { brand:"Patrick Ta", product:"Precision Liner", shade:"She's Dangerous II", price:"$24", hex:"#4A0828" }], [S]: [{ brand:"MAC", product:"Lip Pencil", shade:"Burgundy", price:"$23", hex:"#400020" }, { brand:"MAC", product:"Lip Pencil", shade:"Burgundy II", price:"$23", hex:"#400020" }] },
  blush: { [B]: [{ brand:"Milani", product:"Baked Blush", shade:"Red Vino", price:"$9", hex:"#8B3A5A" }, { brand:"Milani", product:"Baked Blush", shade:"Red Vino II", price:"$9", hex:"#8B3A5A" }], [V]: [{ brand:"Rare Beauty", product:"Soft Pinch", shade:"Grateful", price:"$23", hex:"#7B2040" }, { brand:"Fenty Beauty", product:"Soft Pinch", shade:"Grateful II", price:"$23", hex:"#7B2040" }], [S]: [{ brand:"NARS", product:"Blush", shade:"Seduction", price:"$38", hex:"#6B3060" }, { brand:"Dior Beauty", product:"Blush", shade:"Seduction II", price:"$38", hex:"#6B3060" }] },
  eyes: { [B]: [{ brand:"ColourPop", product:"Super Shock", shade:"Ritz", price:"$6", hex:"#191970" }, { brand:"ColourPop", product:"Super Shock", shade:"Ritz II", price:"$6", hex:"#191970" }], [V]: [{ brand:"Urban Decay", product:"24/7 Shadow", shade:"Ransom", price:"$22", hex:"#4A0E3A" }, { brand:"Urban Decay", product:"24/7 Shadow", shade:"Ransom II", price:"$22", hex:"#4A0E3A" }], [S]: [{ brand:"Tom Ford", product:"Quad", shade:"Badass", price:"$90", hex:"#36454F" }, { brand:"Pat McGrath", product:"Quad", shade:"Badass II", price:"$90", hex:"#36454F" }] },
  bronzer: { [B]: [{ brand:"Wet n Wild", product:"Color Icon", shade:"What Shady Beaches", price:"$5", hex:"#886040" }, { brand:"Wet n Wild", product:"Color Icon", shade:"What Shady Beaches II", price:"$5", hex:"#886040" }], [V]: [{ brand:"Milk Makeup", product:"Matte Bronzer", shade:"Toasted", price:"$28", hex:"#785030" }, { brand:"Milk Makeup", product:"Matte Bronzer", shade:"Toasted II", price:"$28", hex:"#785030" }], [S]: [{ brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Dark", price:"$49", hex:"#684028" }, { brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Dark II", price:"$49", hex:"#684028" }] },
  nails: { [B]: [{ brand:"e.l.f.", product:"Nail Polish", shade:"Dark Berry", price:"$4", hex:"#800020" }, { brand:"NYX", product:"Nail Polish", shade:"Dark Berry II", price:"$4", hex:"#800020" }], [V]: [{ brand:"Glossier", product:"Gel Cream", shade:"Thorn", price:"$14", hex:"#4A0E3A" }, { brand:"Kosas", product:"Gel Cream", shade:"Thorn II", price:"$14", hex:"#4A0E3A" }], [S]: [{ brand:"Tom Ford", product:"Nail Lacquer", shade:"Viper", price:"$37", hex:"#191970" }, { brand:"Pat McGrath", product:"Nail Lacquer", shade:"Viper II", price:"$37", hex:"#191970" }] },
},
"True Winter": {
  foundation: { [B]: [{ brand:"L'Oréal", product:"True Match", shade:"C2 Natural Ivory", price:"$12", hex:"#E8CEC0" }, { brand:"Maybelline", product:"True Match", shade:"C2 Natural Ivory II", price:"$12", hex:"#E8CEC0" }], [V]: [{ brand:"Rare Beauty", product:"Liquid Touch", shade:"150C", price:"$29", hex:"#E8CEC0" }, { brand:"Fenty Beauty", product:"Liquid Touch", shade:"150C II", price:"$29", hex:"#E8CEC0" }], [S]: [{ brand:"Armani Beauty", product:"Luminous Silk", shade:"3", price:"$46", hex:"#E8CEC0" }, { brand:"Charlotte Tilbury", product:"Luminous Silk", shade:"3 II", price:"$46", hex:"#E8CEC0" }] },
  concealer: { [B]: [{ brand:"Maybelline", product:"Instant Age Rewind", shade:"Light/Pale", price:"$10", hex:"#F0DAD0" }, { brand:"L'Oréal", product:"Instant Age Rewind", shade:"Light/Pale II", price:"$10", hex:"#F0DAD0" }], [V]: [{ brand:"Too Faced", product:"Born This Way", shade:"Porcelain", price:"$24", hex:"#F0DAD0" }, { brand:"Too Faced", product:"Born This Way", shade:"Porcelain II", price:"$24", hex:"#F0DAD0" }], [S]: [{ brand:"NARS", product:"Radiant Creamy", shade:"Chantilly", price:"$32", hex:"#F0DAD0" }, { brand:"Dior Beauty", product:"Radiant Creamy", shade:"Chantilly II", price:"$32", hex:"#F0DAD0" }] },
  lips: { [B]: [{ brand:"NYX", product:"Butter Gloss", shade:"Red Velvet", price:"$6", hex:"#FF0000" }, { brand:"e.l.f.", product:"Butter Gloss", shade:"Red Velvet II", price:"$6", hex:"#FF0000" }], [V]: [{ brand:"Rare Beauty", product:"Soft Pinch Liquid", shade:"Powerful", price:"$22", hex:"#B8001F" }, { brand:"Fenty Beauty", product:"Soft Pinch Liquid", shade:"Powerful II", price:"$22", hex:"#B8001F" }], [S]: [{ brand:"Charlotte Tilbury", product:"Matte Revolution", shade:"Red Carpet Red", price:"$35", hex:"#B8252C" }, { brand:"Charlotte Tilbury", product:"Matte Revolution", shade:"Red Carpet Red II", price:"$35", hex:"#B8252C" }] },
  lipLiner: { [B]: [{ brand:"NYX", product:"Suede Matte", shade:"Cherry Skies", price:"$5", hex:"#AA0000" , pairsWith:"Complementary Lipstick" }, { brand:"e.l.f.", product:"Suede Matte", shade:"Cherry Skies II", price:"$5", hex:"#AA0000" }], [V]: [{ brand:"Patrick Ta", product:"Precision Liner", shade:"She's Iconic", price:"$24", hex:"#990033" }, { brand:"Patrick Ta", product:"Precision Liner", shade:"She's Iconic II", price:"$24", hex:"#990033" }], [S]: [{ brand:"MAC", product:"Lip Pencil", shade:"Cherry", price:"$23", hex:"#880022" }, { brand:"MAC", product:"Lip Pencil", shade:"Cherry II", price:"$23", hex:"#880022" }] },
  blush: { [B]: [{ brand:"Milani", product:"Baked Blush", shade:"Fantastico Mauve", price:"$9", hex:"#A05F75" }, { brand:"Milani", product:"Baked Blush", shade:"Fantastico Mauve II", price:"$9", hex:"#A05F75" }], [V]: [{ brand:"Rare Beauty", product:"Soft Pinch", shade:"Bliss", price:"$23", hex:"#C8788C" }, { brand:"Fenty Beauty", product:"Soft Pinch", shade:"Bliss II", price:"$23", hex:"#C8788C" }], [S]: [{ brand:"NARS", product:"Blush", shade:"Desire", price:"$38", hex:"#C71585" }, { brand:"Dior Beauty", product:"Blush", shade:"Desire II", price:"$38", hex:"#C71585" }] },
  eyes: { [B]: [{ brand:"ColourPop", product:"Super Shock", shade:"Amaze", price:"$6", hex:"#C0C0C0" }, { brand:"ColourPop", product:"Super Shock", shade:"Amaze II", price:"$6", hex:"#C0C0C0" }], [V]: [{ brand:"Urban Decay", product:"24/7 Shadow", shade:"Evidence", price:"$22", hex:"#0047AB" }, { brand:"Urban Decay", product:"24/7 Shadow", shade:"Evidence II", price:"$22", hex:"#0047AB" }], [S]: [{ brand:"Tom Ford", product:"Quad", shade:"Starry Night", price:"$90", hex:"#046307" }, { brand:"Pat McGrath", product:"Quad", shade:"Starry Night II", price:"$90", hex:"#046307" }] },
  bronzer: { [B]: [{ brand:"e.l.f.", product:"Putty Bronzer", shade:"Feelin' Shady", price:"$7", hex:"#B8A098" }, { brand:"NYX", product:"Putty Bronzer", shade:"Feelin' Shady II", price:"$7", hex:"#B8A098" }], [V]: [{ brand:"Milk Makeup", product:"Matte Bronzer", shade:"Light", price:"$28", hex:"#A89088" }, { brand:"Milk Makeup", product:"Matte Bronzer", shade:"Light II", price:"$28", hex:"#A89088" }], [S]: [{ brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Light/Medium", price:"$49", hex:"#988078" }, { brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Light/Medium II", price:"$49", hex:"#988078" }] },
  nails: { [B]: [{ brand:"e.l.f.", product:"Nail Polish", shade:"True Red", price:"$4", hex:"#FF0000" }, { brand:"NYX", product:"Nail Polish", shade:"True Red II", price:"$4", hex:"#FF0000" }], [V]: [{ brand:"Glossier", product:"Gel Cream", shade:"Fête", price:"$14", hex:"#DC143C" }, { brand:"Kosas", product:"Gel Cream", shade:"Fête II", price:"$14", hex:"#DC143C" }], [S]: [{ brand:"Tom Ford", product:"Nail Lacquer", shade:"Smoke Red", price:"$37", hex:"#722F37" }, { brand:"Pat McGrath", product:"Nail Lacquer", shade:"Smoke Red II", price:"$37", hex:"#722F37" }] },
},
"Bright Winter": {
  foundation: { [B]: [{ brand:"Maybelline", product:"Fit Me Matte", shade:"118 Light Beige", price:"$9", hex:"#E5CCB8" }, { brand:"L'Oréal", product:"Fit Me Matte", shade:"118 Light Beige II", price:"$9", hex:"#E5CCB8" }], [V]: [{ brand:"Rare Beauty", product:"Liquid Touch", shade:"160C", price:"$29", hex:"#E5CCB8" }, { brand:"Fenty Beauty", product:"Liquid Touch", shade:"160C II", price:"$29", hex:"#E5CCB8" }], [S]: [{ brand:"Armani Beauty", product:"Luminous Silk", shade:"3.5", price:"$46", hex:"#E5CCB8" }, { brand:"Charlotte Tilbury", product:"Luminous Silk", shade:"3.5 II", price:"$46", hex:"#E5CCB8" }] },
  concealer: { [B]: [{ brand:"e.l.f.", product:"Hydrating Camo", shade:"Fair Beige", price:"$7", hex:"#F0DCC8" }, { brand:"NYX", product:"Hydrating Camo", shade:"Fair Beige II", price:"$7", hex:"#F0DCC8" }], [V]: [{ brand:"Milk Makeup", product:"Future Fluid", shade:"6", price:"$28", hex:"#F0DCC8" }, { brand:"Milk Makeup", product:"Future Fluid", shade:"6 II", price:"$28", hex:"#F0DCC8" }], [S]: [{ brand:"Pat McGrath", product:"Sublime Perfection", shade:"L4", price:"$38", hex:"#F0DCC8" }, { brand:"Pat McGrath", product:"Sublime Perfection", shade:"L4 II", price:"$38", hex:"#F0DCC8" }] },
  lips: { [B]: [{ brand:"NYX", product:"Butter Gloss", shade:"Strawberry Cheesecake", price:"$6", hex:"#FF1493" }, { brand:"e.l.f.", product:"Butter Gloss", shade:"Strawberry Cheesecake II", price:"$6", hex:"#FF1493" }], [V]: [{ brand:"Rare Beauty", product:"Soft Pinch Liquid", shade:"Happy", price:"$22", hex:"#FF0033" }, { brand:"Fenty Beauty", product:"Soft Pinch Liquid", shade:"Happy II", price:"$22", hex:"#FF0033" }], [S]: [{ brand:"Charlotte Tilbury", product:"Matte Revolution", shade:"Lost Cherry", price:"$35", hex:"#B0182A" }, { brand:"Charlotte Tilbury", product:"Matte Revolution", shade:"Lost Cherry II", price:"$35", hex:"#B0182A" }] },
  lipLiner: { [B]: [{ brand:"NYX", product:"Suede Matte", shade:"Girl, Bye", price:"$5", hex:"#CC0066" , pairsWith:"Complementary Lipstick" }, { brand:"e.l.f.", product:"Suede Matte", shade:"Girl, Bye II", price:"$5", hex:"#CC0066" }], [V]: [{ brand:"Patrick Ta", product:"Precision Liner", shade:"She's Electric", price:"$24", hex:"#BB0055" }, { brand:"Patrick Ta", product:"Precision Liner", shade:"She's Electric II", price:"$24", hex:"#BB0055" }], [S]: [{ brand:"MAC", product:"Lip Pencil", shade:"Magenta", price:"$23", hex:"#AA0044" }, { brand:"MAC", product:"Lip Pencil", shade:"Magenta II", price:"$23", hex:"#AA0044" }] },
  blush: { [B]: [{ brand:"Milani", product:"Baked Blush", shade:"Fantastico Mauve", price:"$9", hex:"#FF69B4" }, { brand:"Milani", product:"Baked Blush", shade:"Fantastico Mauve II", price:"$9", hex:"#FF69B4" }], [V]: [{ brand:"Rare Beauty", product:"Soft Pinch", shade:"Lucky", price:"$23", hex:"#FF1493" }, { brand:"Fenty Beauty", product:"Soft Pinch", shade:"Lucky II", price:"$23", hex:"#FF1493" }], [S]: [{ brand:"NARS", product:"Blush", shade:"Exhibit A", price:"$38", hex:"#DA1884" }, { brand:"Dior Beauty", product:"Blush", shade:"Exhibit A II", price:"$38", hex:"#DA1884" }] },
  eyes: { [B]: [{ brand:"ColourPop", product:"Super Shock", shade:"Liberty", price:"$6", hex:"#1E90FF" }, { brand:"ColourPop", product:"Super Shock", shade:"Liberty II", price:"$6", hex:"#1E90FF" }], [V]: [{ brand:"Urban Decay", product:"24/7 Shadow", shade:"Freelove", price:"$22", hex:"#D0D0E0" }, { brand:"Urban Decay", product:"24/7 Shadow", shade:"Freelove II", price:"$22", hex:"#D0D0E0" }], [S]: [{ brand:"Tom Ford", product:"Quad", shade:"Electric Blue", price:"$90", hex:"#00CED1" }, { brand:"Pat McGrath", product:"Quad", shade:"Electric Blue II", price:"$90", hex:"#00CED1" }] },
  bronzer: { [B]: [{ brand:"Wet n Wild", product:"Color Icon", shade:"Dulce De Leche", price:"$5", hex:"#B09888" }, { brand:"Wet n Wild", product:"Color Icon", shade:"Dulce De Leche II", price:"$5", hex:"#B09888" }], [V]: [{ brand:"Milk Makeup", product:"Matte Bronzer", shade:"Light", price:"$28", hex:"#A08878" }, { brand:"Milk Makeup", product:"Matte Bronzer", shade:"Light II", price:"$28", hex:"#A08878" }], [S]: [{ brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Light/Medium", price:"$49", hex:"#907868" }, { brand:"Charlotte Tilbury", product:"Filmstar Bronze", shade:"Light/Medium II", price:"$49", hex:"#907868" }] },
  nails: { [B]: [{ brand:"e.l.f.", product:"Nail Polish", shade:"Hot Pink", price:"$4", hex:"#FF1493" }, { brand:"NYX", product:"Nail Polish", shade:"Hot Pink II", price:"$4", hex:"#FF1493" }], [V]: [{ brand:"Glossier", product:"Gel Cream", shade:"Petal", price:"$14", hex:"#FF6B81" }, { brand:"Kosas", product:"Gel Cream", shade:"Petal II", price:"$14", hex:"#FF6B81" }], [S]: [{ brand:"Tom Ford", product:"Nail Lacquer", shade:"Azalea", price:"$37", hex:"#C71585" }, { brand:"Pat McGrath", product:"Nail Lacquer", shade:"Azalea II", price:"$37", hex:"#C71585" }] },
},
};

export function getProductRecommendations(seasonName) {
  const seasonProducts = productDB[seasonName];
  if (!seasonProducts) return { categories: [], tierMeta: TIER_META };
  const categories = CATEGORIES.map((cat) => ({
    ...cat,
    tiers: seasonProducts[cat.key] || null,
  })).filter((cat) => cat.tiers !== null);
  return { categories, tierMeta: TIER_META };
}

export { TIER_META, CATEGORIES };
