export const questions = [
  {
    id: 1,
    question: "What color are your wrist veins in natural daylight?",
    subtitle: "Look at the inside of your wrist under natural light",
    options: [
      { label: "Green or greenish", value: "green", color: "#5a8a6a" },
      { label: "Blue or purple", value: "blue", color: "#6a5a8a" },
      { label: "Mix of both", value: "mix", color: "#6a7a8a" },
      { label: "Hard to tell", value: "unsure", color: "#9a9a9a" },
    ],
  },
  {
    id: 2,
    question: "Which metal looks more flattering against your skin?",
    subtitle: "Think about jewelry you've worn or hold metal near your face",
    options: [
      { label: "Gold", value: "gold", color: "#D4A843" },
      { label: "Silver", value: "silver", color: "#C0C0C0" },
      { label: "Both equally", value: "both", color: "#B8A88A" },
      { label: "Not sure", value: "unsure", color: "#9a9a9a" },
    ],
  },
  {
    id: 3,
    question: "How does your skin react to sun exposure?",
    subtitle: "Think about your typical response to spending time outdoors",
    options: [
      { label: "I tan quickly, rarely burn", value: "tan", color: "#C99A6B" },
      { label: "I burn first, then tan", value: "burn", color: "#E8A0A0" },
      { label: "Balanced. I tan and burn equally", value: "balanced", color: "#C9A090" },
      { label: "I'm rarely in the sun", value: "unsure", color: "#9a9a9a" },
    ],
  },
  {
    id: 4,
    question: "Do foundations often look too pink OR too yellow on you?",
    subtitle: "This can be a sign of olive undertones",
    options: [
      { label: "Yes, frequently", value: "yes" },
      { label: "No, I find good matches", value: "no" },
      { label: "Not sure", value: "unsure" },
    ],
  },
  {
    id: 5,
    question: "What's your natural hair color?",
    subtitle: "Choose the closest match to your uncolored hair",
    options: [
      { label: "Light/golden blonde or strawberry blonde", value: "light_warm", color: "#D4B483" },
      { label: "Ash blonde or cool light brown", value: "light_cool", color: "#A89070" },
      { label: "Golden brown, auburn, or chestnut", value: "deep_warm", color: "#7B4B2A" },
      { label: "Dark brown or black", value: "deep_cool", color: "#2B1D0E" },
    ],
  },
  {
    id: 6,
    question: "How dark is your natural hair?",
    subtitle: "Consider the overall depth of your hair color",
    options: [
      { label: "Light or medium-light", value: "light", color: "#C4A877" },
      { label: "Medium", value: "medium", color: "#7B5B3A" },
      { label: "Dark or very dark", value: "dark", color: "#2B1D0E" },
    ],
  },
  {
    id: 7,
    question: "How would you describe your skin tone?",
    subtitle: "Match your depth, not your undertone. Look at the inside of your arm for the most accurate read.",
    options: [
      { label: "Very fair / porcelain", value: "very_fair", color: "linear-gradient(135deg, #FFF0E5 0%, #F5D5C0 100%)" },
      { label: "Fair", value: "fair", color: "linear-gradient(135deg, #FDE7D6 0%, #EABFA6 100%)" },
      { label: "Light-medium", value: "light_medium", color: "linear-gradient(135deg, #EDCBB5 0%, #D8AE8C 100%)" },
      { label: "Medium", value: "medium", color: "linear-gradient(135deg, #D6AD89 0%, #BA8960 100%)" },
      { label: "Medium-deep", value: "medium_deep", color: "linear-gradient(135deg, #A87A54 0%, #875936 100%)" },
      { label: "Deep / Rich", value: "deep", color: "linear-gradient(135deg, #6B4228 0%, #452514 100%)" },
    ],
  },
  {
    id: 8,
    question: "What's your natural eye color?",
    subtitle: "Look closely. Check in natural daylight for the most accurate read",
    options: [
      { label: "Light blue, green, or light hazel", value: "light", color: "#7BA7BC" },
      { label: "Medium brown, green, or hazel", value: "medium", color: "#8B7355" },
      { label: "Dark brown or very dark", value: "dark", color: "#3B2B1B" },
    ],
  },
  {
    id: 9,
    question: "How bright and clear are your eyes?",
    subtitle: "Do your eyes catch attention, or do they blend softly with your features?",
    options: [
      { label: "Very bright and vivid. They stand out", value: "bright", color: "#4FC1E9" },
      { label: "Soft and muted. They blend with my features", value: "soft", color: "#B5B8A3" },
      { label: "Somewhere in between", value: "between", color: "#8BA3A0" },
    ],
  },
  {
    id: 10,
    question: "What's the contrast between your hair, skin, and eyes?",
    subtitle: "Compare the lightness/darkness of your features to each other",
    options: [
      {
        label: "Low. My features are all similar in lightness",
        value: "low",
        visual: "low_contrast",
        description: "e.g., light skin + light hair + light eyes",
      },
      {
        label: "Medium. Moderate difference between features",
        value: "medium",
        visual: "medium_contrast",
        description: "e.g., medium skin + brown hair + hazel eyes",
      },
      {
        label: "High. Stark difference between features",
        value: "high",
        visual: "high_contrast",
        description: "e.g., fair skin + dark hair + dark eyes",
      },
    ],
  },
  {
    id: 11,
    question: "Which of these color stories feels most like you?",
    subtitle: "Pick the palette you'd actually reach for, or the one you get the most compliments in",
    options: [
      {
        label: "Bright corals, warm pinks, and citrus tones",
        value: "spring",
        swatches: ["#FF6B6B", "#FF7F50", "#FFDAB9", "#FFD700"],
        description: "Think tropical vacation, golden hour, warm energy",
      },
      {
        label: "Soft dusty roses, muted mauves, and lavender",
        value: "summer",
        swatches: ["#C9929D", "#B0A4C4", "#D4A0C0", "#9EB1BD"],
        description: "Think soft romance, misty mornings, understated elegance",
      },
      {
        label: "Rich terracottas, olive greens, and burnt orange",
        value: "autumn",
        swatches: ["#CC6633", "#556B2F", "#A0522D", "#CD853F"],
        description: "Think cozy spice, earthy warmth, vintage vibes",
      },
      {
        label: "Electric blues, vivid pinks, and true reds",
        value: "winter",
        swatches: ["#DC143C", "#4169E1", "#FF1493", "#00CED1"],
        description: "Think bold drama, high contrast, statement pieces",
      },
      {
        label: "Warm nudes, peachy neutrals, and caramel tones",
        value: "spring",
        swatches: ["#E8C4A8", "#FFDAB9", "#D4A574", "#FFB7A5"],
        description: "Think effortless warmth, natural glow, golden skin",
      },
      {
        label: "Cool-toned berries, wine, and deep plum",
        value: "winter",
        swatches: ["#722F37", "#800020", "#8B3A62", "#4A0E3A"],
        description: "Think rich nights out, moody sophistication, deep contrast",
      },
      {
        label: "Warm metallics: bronze, copper, and warm gold",
        value: "autumn",
        swatches: ["#B8860B", "#B87333", "#CD853F", "#DAA520"],
        description: "Think warm shimmer, golden jewelry, luxe warmth",
      },
      {
        label: "Icy pastels, powder blue, and soft silver",
        value: "summer",
        swatches: ["#B0C4DE", "#E6E6FA", "#ADD8E6", "#F7CAC9"],
        description: "Think light and airy, cool breeze, soft glow",
      },
    ],
  },
  {
    id: 12,
    question: "Hold white paper then cream paper near your face. Which makes your skin look better?",
    subtitle: "Try this in natural daylight for the best comparison",
    options: [
      { label: "White looks better", value: "white", color: "#FFFFFF", border: true },
      { label: "Cream looks better", value: "cream", color: "#FFFDD0" },
      { label: "Both look similar", value: "both", color: "#F5F5F0" },
      { label: "I'll skip this one", value: "skip", color: "#E0E0E0" },
    ],
  },
];
