/**
 * Vibe DNA — 11 Aesthetic Archetype definitions.
 * Each includes copy, moodboard, celebrity twins, share tagline, and accent styling.
 */

export const archetypeNames = {
  CG: "Clean Girl",
  COG: "Coastal Grandmother",
  OM: "Quiet Luxury",
  DA: "Dark Academia",
  CT: "Cottagecore",
  CQ: "Coquette",
  Y2K: "Y2K Revival",
  BC: "Balletcore",
  SM: "Scandi Minimalist",
  IS: "Indie Sleaze",
  TL: "Tomboy Luxe",
};

export const archetypes = {
  CG: {
    name: "Clean Girl",
    code: "CG",
    accentColor: "#C4A265",
    bgGradient: "linear-gradient(145deg, #FFFBF7 0%, #F5EDE4 40%, #EDE5D8 100%)",
    description: "Your aesthetic is effortless polish — the kind that takes thirty minutes but reads as five. You gravitate toward investment basics, skin-that-looks-like-skin beauty, and the confidence of understatement. You're not trying to be noticed; you're trying to feel good in your own quietness.",
    pills: ["Understated", "Polished"],
    moodboard: ["Slicked bun", "Gold hoop", "White tee", "Oat milk matcha", "Pilates mat", "Dewy skin", "Linen sheets", "Clear lip gloss"],
    moodboardEmojis: ["💫", "⭕", "👕", "🍵", "🧘‍♀️", "✨", "🤍", "💋"],
    celebrities: ["Hailey Bieber", "Sofia Richie", "Matilda Djerf"],
    shareTagline: "Quiet confidence. Gold hoops. Never the loudest in the room.",
    proTips: {
      top: "The tee should be thick enough to layer under a blazer without showing a bra line. Test it in natural light before committing.",
      bottom: "Straight-leg jeans in a mid-rise live longest — avoid anything that reads \"trend\" more than \"wardrobe.\"",
      layer: "An oversized blazer in black or cream is your single best ROI. Tailor the shoulders, not the length.",
      shoes: "Clean Girl sneakers live and die by the white. Keep a magic eraser in your bag and replace them every 9 months.",
      bag: "One structured top-handle in a neutral, one soft shoulder bag in leather. You don't need a third.",
      jewelry: "Never more than three pieces at once. The point is that nothing fights for attention.",
      fragrance: "Layer a skin-musk over a hydrating body oil — the scent lasts longer and smells like you, not perfume.",
      finishing: "A slicked bun reads richer when the product is clear, not white. Use gel, not wax.",
    },
  },
  COG: {
    name: "Coastal Grandmother",
    code: "COG",
    accentColor: "#7B8E6B",
    bgGradient: "linear-gradient(145deg, #FFFBF7 0%, #EEF1E8 40%, #E2E8D8 100%)",
    description: "Your aesthetic is the Nancy Meyers fantasy made real — linen that wrinkles in the right way, gardens you actually tend, and a life designed for slow mornings. You collect ceramic bowls, you know what looks good in natural light, and you believe in real butter. Age is a vibe, not a number.",
    pills: ["Serene", "Timeless"],
    moodboard: ["Linen robe", "Blue hydrangeas", "Wicker basket", "Straw hat", "Garden tomatoes", "Espresso cup", "White slipcover", "Woven sandals"],
    moodboardEmojis: ["🥻", "💐", "🧺", "👒", "🍅", "☕", "🤍", "👡"],
    celebrities: ["Diane Keaton", "Ina Garten", "Sienna Miller"],
    shareTagline: "Linen. Hydrangeas. A life built around good light.",
    proTips: {
      top: "A man's-cut linen button-down in cream or white — size up. Rolled sleeves, never perfectly pressed.",
      bottom: "Wide-leg linen pants in sand or navy. If they don't look slightly rumpled, they're too formal.",
      layer: "A single cashmere cardigan in oatmeal, left unbuttoned and pushed up at the elbows.",
      shoes: "Espadrilles for summer, suede loafers for shoulder season. White sneakers only when gardening.",
      bag: "Woven basket tote for the market, straw crossbody for evening. No logos.",
      jewelry: "One pair of pearl studs (small), a thin gold chain, a watch with a leather strap. That's the full kit.",
      fragrance: "Bergamot and sea salt for day, garden herbs for evening. Nothing sweet.",
      finishing: "A straw hat you've owned for three summers beats a new one every time. Let it bend.",
    },
  },
  OM: {
    name: "Quiet Luxury",
    code: "OM",
    accentColor: "#8B7355",
    bgGradient: "linear-gradient(145deg, #FFFBF7 0%, #F0EAE0 40%, #E8DFD0 100%)",
    description: "Your aesthetic is heritage without effort — investment pieces, quiet logos, and the sense that your wardrobe was inherited, not shopped. You don't chase trends because you've already decided what looks good. Your style is a long game, and it's winning.",
    pills: ["Investment", "Understated"],
    moodboard: ["Cashmere crewneck", "Pearl studs", "Monogrammed tote", "Leather loafers", "Tennis bracelet", "Silk scarf", "Trench coat", "Vintage watch"],
    moodboardEmojis: ["🧶", "🫧", "👜", "👞", "💎", "🧣", "🧥", "⌚"],
    celebrities: ["Carolyn Bessette-Kennedy", "Sofia Richie", "Rosie Huntington-Whiteley"],
    shareTagline: "If you have to ask the brand, it's not the vibe.",
    proTips: {
      top: "Cashmere crewneck in oatmeal, navy, or camel. Check the ply — 2-ply minimum, 4-ply if you can stretch.",
      bottom: "Pleated wool trousers, cuffed at the ankle. Tailoring is non-negotiable.",
      layer: "The trench coat is the investment. Classic beige, knee-length, belted not buttoned.",
      shoes: "Leather loafers in tan or burgundy, resoled every 18 months. They should age visibly.",
      bag: "One structured tote in saddle or black leather. Monogram is optional; patina is not.",
      jewelry: "Pearl studs, a tennis bracelet, a signet ring if inherited. Never costume.",
      fragrance: "Tobacco, amber, or a single-note floral worn for a decade. You smell like a person, not a brand.",
      finishing: "A silk scarf tied three ways — neck, handbag handle, or in your hair. Know all three.",
    },
  },
  DA: {
    name: "Dark Academia",
    code: "DA",
    accentColor: "#6B4E3D",
    bgGradient: "linear-gradient(145deg, #FFFBF7 0%, #EDE4DA 40%, #DDD1C2 100%)",
    description: "Your aesthetic lives in libraries, European autumns, and the light coming through a stained-glass window at 4pm. You romanticize the pursuit of knowledge, collect vintage books you'll actually read, and own at least one tweed blazer with elbow patches. Melancholy is a color palette.",
    pills: ["Intellectual", "Romantic"],
    moodboard: ["Tweed blazer", "Stacked books", "Library lamp", "Leather satchel", "Autumn leaves", "Vintage typewriter", "Signet ring", "Black coffee"],
    moodboardEmojis: ["🧥", "📚", "🪔", "💼", "🍂", "⌨️", "💍", "☕"],
    celebrities: ["Emma Watson", "Timothée Chalamet", "Jenna Ortega"],
    shareTagline: "Autumn light. Library stacks. The romance of knowing things.",
    proTips: {
      top: "A cable-knit turtleneck or ivory silk blouse with a pussy bow. Cotton over polyester, always.",
      bottom: "Pleated midi skirt in wool plaid, or tailored trousers in tobacco brown.",
      layer: "A tweed blazer, ideally with elbow patches — or add them yourself to a thrifted find.",
      shoes: "Vintage Mary Janes or oxfords. New ones should look broken in within a week.",
      bag: "Leather satchel with a buckle, ideally slightly scuffed. A new bag undoes the whole aesthetic.",
      jewelry: "A signet ring, a vintage watch, one pair of small gold or pearl earrings. Nothing shiny.",
      fragrance: "Tobacco, leather, old paper, amber. The fragrance should smell like a library at dusk.",
      finishing: "Reading glasses (with or without prescription) and a pen tucked behind the ear. Commit.",
    },
  },
  CT: {
    name: "Cottagecore",
    code: "CT",
    accentColor: "#9B7B5E",
    bgGradient: "linear-gradient(145deg, #FFFBF7 0%, #F4EDE2 40%, #ECE3D5 100%)",
    description: "Your aesthetic is pastoral romance — the fantasy of baking bread in a cottage, tending a garden, and living by the rhythms of seasons instead of notifications. You love what's handmade, mended, and imperfect. Your Pinterest is 80% light through old windows.",
    pills: ["Pastoral", "Romantic"],
    moodboard: ["Pressed flowers", "Sourdough loaf", "Gingham apron", "Garden basket", "Vintage wallpaper", "Honey jar", "Prairie dress", "Beeswax candle"],
    moodboardEmojis: ["🌸", "��", "👗", "🧺", "🏡", "🍯", "👗", "🕯️"],
    celebrities: ["Taylor Swift", "Florence Pugh", "Stevie Nicks"],
    shareTagline: "Pastoral soul. Honey jars. Bread rising on the counter.",
    proTips: {
      top: "Prairie blouse with puff sleeves, or a Peter Pan collar in ivory. Look for vintage or handmade.",
      bottom: "A prairie dress or gathered skirt with pockets — pockets are non-negotiable.",
      layer: "A hand-knit cardigan with wooden buttons. Imperfect stitches mean it's real.",
      shoes: "Leather Mary Janes, vintage boots, or clogs. Clean them rarely.",
      bag: "A woven market basket, not a purse. Bread and flowers live there.",
      jewelry: "A locket with a pressed flower inside, a thin gold chain, stud earrings. Everything should have a story.",
      fragrance: "Rose, honey, beeswax, fresh laundry. Think garden, not perfume counter.",
      finishing: "A braid with ribbon, flour dust on your apron, cheeks pink from kneading dough.",
    },
  },
  CQ: {
    name: "Coquette",
    code: "CQ",
    accentColor: "#D4869C",
    bgGradient: "linear-gradient(145deg, #FFFBF7 0%, #FBE8EE 40%, #F5D4E0 100%)",
    description: "Your aesthetic is soft-girl romance — bows in your hair, pink on your lips, and the confidence to be unapologetically feminine in a world that keeps trying to iron it out. You love what's pretty, you're not sorry about it, and you collect things that feel like love letters.",
    pills: ["Feminine", "Romantic"],
    moodboard: ["Pink bow", "Pearl necklace", "Lace trim", "Rosé wine", "Ballet flat", "Heart-shaped locket", "Satin ribbon", "Strawberry"],
    moodboardEmojis: ["🎀", "📿", "🤍", "🍷", "🩰", "💝", "🎗️", "🍓"],
    celebrities: ["Lana Del Rey", "Sabrina Carpenter", "Sydney Sweeney"],
    shareTagline: "Bows, pearls, and zero apologies.",
    proTips: {
      top: "A wrap top, satin camisole, or puff-sleeve blouse in blush or cream. Lace trim is encouraged.",
      bottom: "A pleated mini skirt, or high-waist denim paired with something soft on top.",
      layer: "A cropped cardigan in cherry red or baby pink — vintage preferred.",
      shoes: "Ballet flats with ribbon ties, Mary Janes, or kitten heels. Always feminine.",
      bag: "A small crossbody or top-handle in satin or patent, ideally with a bow.",
      jewelry: "Pearls — layered, doubled, everywhere. A bow-shaped ring. A heart locket.",
      fragrance: "Rose, vanilla, strawberry, peony. Sweet without apology.",
      finishing: "One ribbon in your hair, blush on the apples of your cheeks, lip stain not lipstick.",
    },
  },
  Y2K: {
    name: "Y2K Revival",
    code: "Y2K",
    accentColor: "#C96BBE",
    bgGradient: "linear-gradient(145deg, #FFFBF7 0%, #F5E3F4 40%, #EDDDE8 100%)",
    description: "Your aesthetic pulls from 1999-2004 — low-rise, metallic, slightly chaotic, deeply fun. You grew up (or wish you had) in the era of butterfly clips, Juicy tracksuits, and Britney Spears music videos, and you're bringing the confidence forward. Nothing is too much.",
    pills: ["Nostalgic", "Bold"],
    moodboard: ["Butterfly clip", "Low-rise denim", "Metallic top", "Platform sandal", "Heart sunglasses", "Body glitter", "Silver hoop", "Glossy lip"],
    moodboardEmojis: ["🦋", "👖", "✨", "👡", "🕶️", "💫", "⭕", "💋"],
    celebrities: ["Bella Hadid", "Dua Lipa", "Olivia Rodrigo"],
    shareTagline: "Low-rise. High-confidence. The 2000s called — you answered.",
    proTips: {
      top: "A metallic halter, baby tee, or tube top. Graphic print earns bonus points.",
      bottom: "Low-rise denim, mini skirt, or a rhinestone belt over either. Waistbands matter.",
      layer: "A cropped track jacket, a fur-trim cardigan, or a vintage Juicy zip-up.",
      shoes: "Platform sandals, chunky sneakers, or kitten-heel mules. Height is the point.",
      bag: "A tiny shoulder bag with a short strap — vintage Coach or a monogrammed dupe.",
      jewelry: "Chokers, hoop earrings, belly chain, silver over gold. Pile it on.",
      fragrance: "Pink sugar, vanilla, bubblegum, or a fruity top note. Escapist and nostalgic.",
      finishing: "Butterfly clips, body glitter, glossy lip. The more, the more.",
    },
  },
  BC: {
    name: "Balletcore",
    code: "BC",
    accentColor: "#C9929B",
    bgGradient: "linear-gradient(145deg, #FFFBF7 0%, #F9E8EB 40%, #F0DDE0 100%)",
    description: "Your aesthetic is discipline wrapped in softness — pink, pointe shoes, and the quiet strength of something beautiful that took years to build. You love ribbons, wrap tops, and the specific pink of a ballet slipper. You move through the world carefully, and it shows.",
    pills: ["Graceful", "Disciplined"],
    moodboard: ["Satin ribbon", "Wrap sweater", "Tulle skirt", "Ballet slipper", "Pink blush", "Pearl bobby pin", "Leotard", "Rosin box"],
    moodboardEmojis: ["🎗️", "🧶", "👗", "🩰", "🌸", "📌", "🩱", "📦"],
    celebrities: ["Natalie Portman", "Misty Copeland", "Devon Lee Carlson"],
    shareTagline: "Pink ribbons. Quiet discipline. Soft but never small.",
    proTips: {
      top: "Wrap top, long-sleeve leotard-style, or cropped cashmere. Pink, cream, or ballet-slipper gray.",
      bottom: "Tulle midi skirt, leg warmers over tights, or high-waist wide-leg trousers.",
      layer: "A wrap cardigan tied at the waist, or a warm-up jacket in dusty pink.",
      shoes: "Ballet flats with ribbon ties — real ones, not slip-ons. They need to tie.",
      bag: "A small structured bag in satin or nylon, ideally with a ribbon detail.",
      jewelry: "Pearl bobby pins worn as jewelry, a thin gold chain, small stud earrings.",
      fragrance: "Soft florals — iris, peony, white tea. Nothing heavy or gourmand.",
      finishing: "A low bun with a satin ribbon, pink blush high on the cheeks, nude lip.",
    },
  },
  SM: {
    name: "Scandi Minimalist",
    code: "SM",
    accentColor: "#7A7A7A",
    bgGradient: "linear-gradient(145deg, #FFFBF7 0%, #EDEDEB 40%, #E2E2DF 100%)",
    description: "Your aesthetic is architectural — clean lines, negative space, and the belief that one perfect object is worth more than ten decent ones. You dress for form, you decorate for light, and you edit until only what matters is left. Hygge without the cliché.",
    pills: ["Architectural", "Edited"],
    moodboard: ["Black turtleneck", "Architectural earring", "Wool coat", "White space", "Bouclé chair", "One ceramic vase", "Wide-leg trouser", "Matte skin"],
    moodboardEmojis: ["🖤", "📐", "🧥", "🤍", "🪑", "🏺", "👖", "✨"],
    celebrities: ["Matilda Djerf", "Pernille Teisbaek", "Tilda Swinton"],
    shareTagline: "Less, but better. Always.",
    proTips: {
      top: "A black turtleneck or white oversized button-down. The fabric should hang, not cling.",
      bottom: "Wide-leg wool trouser or straight-leg denim in a dark rinse. Length matters more than cost.",
      layer: "A long wool coat in camel, charcoal, or black. Double-faced if you can find it.",
      shoes: "Leather Chelsea boots, black loafers, or architectural sneakers. One pair per category.",
      bag: "A single structured bag in black or cognac leather. Minimal hardware.",
      jewelry: "One architectural earring, one thin band ring. Negative space is the design.",
      fragrance: "Fig, sandalwood, cedarwood. Warm and unisex.",
      finishing: "Matte skin, minimal makeup, hair slicked or air-dried. The look is \"expensive on purpose.\"",
    },
  },
  IS: {
    name: "Indie Sleaze",
    code: "IS",
    accentColor: "#8B4A4A",
    bgGradient: "linear-gradient(145deg, #FFFBF7 0%, #EDE0D8 40%, #DDD0C6 100%)",
    description: "Your aesthetic is a little undone, a little chaotic, and entirely intentional. You thrift before you shop, you layer without thinking, and your eyeliner is smudged because it looks better that way. You\u2019d rather be interesting than pretty \u2014 though you\u2019re usually both.",
    pills: ["Gritty", "Effortless"],
    moodboard: ["Vintage band tee", "Leather jacket", "Smudged liner", "Messy hair", "Vinyl records", "Doc Martens", "Silver rings", "Red lip"],
    moodboardEmojis: ["\ud83c\udfb8", "\ud83e\udde5", "\ud83d\udda4", "\ud83d\udc87\u200d\u2640\ufe0f", "\ud83d\udcbf", "\ud83d\udc62", "\ud83e\udea9", "\ud83d\udc8b"],
    celebrities: ["Zo\u00eb Kravitz", "Alexa Chung", "Kristen Stewart"],
    shareTagline: "Smudged liner. Thrifted leather. Beautifully unbothered.",
    proTips: {
      top: "A vintage band tee, slightly oversized, ideally from an actual gig. Faded > pristine.",
      bottom: "Black skinny jeans or a vintage-wash straight leg. Rips are optional but encouraged.",
      layer: "A leather jacket that\u2019s been lived in. If it\u2019s new, wear it in the rain.",
      shoes: "Doc Martens, worn-in Chelsea boots, or beat-up Converse. Clean shoes ruin the whole thing.",
      bag: "A vintage crossbody in black leather, or a canvas tote from a bookshop you\u2019ve actually been to.",
      jewelry: "Stack silver rings on every finger. Mix chunky chains with delicate. More is more, but all silver.",
      fragrance: "Patchouli, cedar, black coffee, a little smoke. You should smell like a late night.",
      finishing: "Smudged black liner, undone hair, and a red lip that you applied without a mirror.",
    },
  },
  TL: {
    name: "Tomboy Luxe",
    code: "TL",
    accentColor: "#5A6B5A",
    bgGradient: "linear-gradient(145deg, #FFFBF7 0%, #E8EBE5 40%, #DEE2D8 100%)",
    description: "Your aesthetic is borrowed-from-the-boys but elevated \u2014 oversized suits that fit perfectly wrong, crisp button-downs with nothing underneath, and the confidence to wear menswear better than men do. You blur the line between masculine and feminine and make it look expensive.",
    pills: ["Androgynous", "Powerful"],
    moodboard: ["Oversized blazer", "Crisp white shirt", "Loafers", "Slicked hair", "Watch face", "Tailored trousers", "Oxford shoes", "No jewelry"],
    moodboardEmojis: ["\ud83e\udde5", "\ud83d\udc54", "\ud83d\udc5e", "\ud83d\udc87\u200d\u2640\ufe0f", "\u231a", "\ud83d\udc56", "\ud83d\udc5f", "\u2728"],
    celebrities: ["Zendaya", "Evan Rachel Wood", "Janelle Mon\u00e1e"],
    shareTagline: "Borrowed from the boys. Wore it better.",
    proTips: {
      top: "An oversized white button-down or a fitted crew-neck undershirt. Buy from the men\u2019s section \u2014 better fabric.",
      bottom: "Wide-leg tailored trousers with a masculine cut. Have them hemmed to show ankle.",
      layer: "A double-breasted blazer, ideally in charcoal or navy. Oversized in the shoulders, cropped nothing.",
      shoes: "Oxford lace-ups, monk straps, or chunky loafers. Polish them. The shine is the feminine touch.",
      bag: "A structured briefcase-style bag or a leather backpack. Nothing with a chain strap.",
      jewelry: "One statement watch, maybe a thin chain. The restraint is the point.",
      fragrance: "Vetiver, cedar, bergamot, white musk. Something your dad would compliment.",
      finishing: "Slicked-back hair, bare face, one bold lip. Let the clothes do the talking.",
    },
  },
};